### ISSUE TITLE
0 reference calls error

### ISSUE THREAD

**Issue by Jucarvag** [cancerit/NanoSeq#101]
Hi,
I am doing Nano-seq with human cells for the first time (I have been doing it with other species and it it has worked fine) and I am getting this error in the nanoseq_results_plotter.R: "ValueError: 0 reference calls. Exiting".
Do you have any ideas why this would happen?
I have tried with both GRCh37 and 38 (with their respective SNP and NOISE files).
For what I can see, the steps previous to running runNanoSeq.py are working well.
Thanks very much

**Comment by fa8sanger** [comment]
Hi, it’s difficult to know from here. It could be that there is very low duplicate rate, then the duplex consensus is never reached. But 0 reference calls is really too few. Have you checked the duplicate rate?

Another factor that may give 0 reference calls is when you use as matched normal a sample with very low coverage, always below the threshold.

Have a look at those things and let me know


On 29 Jul 2024, at 15:23, Jucarvag ***@***.***> wrote:



Hi,
I am doing Nano-seq with human cells for the first time (I have been doing it with other species and it it has worked fine) and I am getting this error in the nanoseq_results_plotter.R: "ValueError: 0 reference calls. Exiting".
Do you have any ideas why this would happen?
I have tried with both GRCh37 and 38 (with their respective SNP and NOISE files).
For what I can see, the steps previous to running runNanoSeq.py are working well.
Thanks very much

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_101&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=_DfjrA4WNZba4Bn-XUynG6BwSLIb2ZEG_Gs1zoM6QFNSH4rjpplzD2H2u-LPp5cs&s=uI0SUZNiRfQ-M7Zp3YYXc95tljbM3e5LHW9hKQaZbRY&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3K4DFDC6QKKH55ZODLZOZF6XAVCNFSM6AAAAABLUMVWMWVHI2DSMVQWIX3LMV43ASLTON2WKOZSGQZTKNJXGIYTQNQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=_DfjrA4WNZba4Bn-XUynG6BwSLIb2ZEG_Gs1zoM6QFNSH4rjpplzD2H2u-LPp5cs&s=l2G6mQ5Vl5T9--gr_JePP4cga_vFpcDzu40Ta7j8Www&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by Jucarvag** [comment]
Thanks for responding so quickly!
My duplication rate (calculated with efficiency_nanoseq.pl) is 72%.
Filtered reads: 4x10^7 
Neat reads: 1X10^7
I run the efficiency on the normals,
Filtered-normal: 2.2x10^6
Neat-normal:  1.8x10^6

**Comment by fa8sanger** [comment]
Do you only have 2.2 million reads in the matched normal? That’s super low coverage. That must be why you didn’t get any call
________________________________

**Comment by Jucarvag** [comment]
That's interesting. For my normals, I have always aimed to have 5%-10% of the reads I have for my nanoseqs.
I guess that works well for smaller genomes but not so much for human cells.
Should I aim to have the same number of reads in both normals and nanoseqs?

**Comment by fa8sanger** [comment]
For a good matched normal you need at least 10x which later translates in higher coverage because Nanoseq only sees part of the genome (restriction enzyme digestion).
________________________________

**Comment by Jucarvag** [comment]
Perfect, thanks very much!
