### ISSUE TITLE
Can efficiency_nanoseq.pl count 'rb' tag correctly?

### ISSUE THREAD

**Issue by monagai** [cancerit/NanoSeq#102]
Because extract_tags.py sets `rb` tag not `RB`, efficiency_nanoseq.pl does not seem to count `rb` tag correctly.
https://github.com/cancerit/NanoSeq/blob/4136d3ca943b96b2cf9013ac14183f098b8234be/perl/efficiency_nanoseq.pl#L149-L154

**Comment by fa8sanger** [comment]
After running extract_tags.py you need to remap and then run bamaddreadbundles which will add the rb tag correctly

On 7 Aug 2024, at 10:02, Momoko NAGAI ***@***.***> wrote:



Because extract_tags.py sets rb tag not RB, efficiency_nanoseq.pl does not seem to count rb tag correctly.
https://github.com/cancerit/NanoSeq/blob/4136d3ca943b96b2cf9013ac14183f098b8234be/perl/efficiency_nanoseq.pl#L149-L154 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_blob_4136d3ca943b96b2cf9013ac14183f098b8234be_perl_efficiency-5Fnanoseq.pl-23L149-2DL154&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=F-H_vPRdO8pv0hJFH3n2p5X5CHLXQoKcuKC4fS6RfXyBShTU_PwuLkwV-UiC6EO7&s=Xt7TMLFA7k7a4Fg0X41vA37tUZ_laUnolCVeGCDE2kU&e=>

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_102&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=F-H_vPRdO8pv0hJFH3n2p5X5CHLXQoKcuKC4fS6RfXyBShTU_PwuLkwV-UiC6EO7&s=NTRuUagKYBfnjQwkTrxNnmVyPDubS4xdX-jc4HDgMiU&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3O4HON7VBDYKQ6BI7TZQHPC5AVCNFSM6AAAAABMD6OVMCVHI2DSMVQWIX3LMV43ASLTON2WKOZSGQ2TEOJVHAYTCMQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=F-H_vPRdO8pv0hJFH3n2p5X5CHLXQoKcuKC4fS6RfXyBShTU_PwuLkwV-UiC6EO7&s=yOTM1xV0lRP03ze1-XVxOcNrLlR9fI57zbk-KtKDQW8&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by monagai** [comment]
Thank you for your comment.

> After running extract_tags.py you need to remap and then run bamaddreadbundles which will add the rb tag correctly

I did so.
However, I used NanoSeq 3.5.1. because Nanoseq 3.5.4 sometimes failed for my date.
It may be the cause.
Thank you.

**Comment by fa8sanger** [comment]
Hi Momoko,

It should have worked. Do you still have the problem?


On 19 Aug 2024, at 03:36, Momoko NAGAI ***@***.***> wrote:



Thank you for your comment.

After running extract_tags.py you need to remap and then run bamaddreadbundles which will add the rb tag correctly

I did so.
However, I used NanoSeq 3.5.1. because Nanoseq 3.5.4 sometimes failed for my data.
It may be the cause.
Thank you.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_102-23issuecomment-2D2295557010&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=DNHk_Pv3LtQkjdhxUAtIozXNDzMbquRN5Sce0ezWN02NshxvUUCOrTmLUUvMICKb&s=eIHOFeX32owz3L2pE_Cp1h_zYUVO5N4kPoh2zyrTXnY&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3JAYOE3PNYHCMO4NKTZSFK2XAVCNFSM6AAAAABMD6OVMCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJVGU2TOMBRGA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=DNHk_Pv3LtQkjdhxUAtIozXNDzMbquRN5Sce0ezWN02NshxvUUCOrTmLUUvMICKb&s=0ICdAR9_M97W9HQHsCOoTdjpv9RA51BJLuRqsy9JzhA&e=>.
You are receiving this because you commented.Message ID: ***@***.***>


----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by monagai** [comment]
> It should have worked. Do you still have the problem?

Thank you for your comment.
It may be a problem of our data, not NanoSeq.
Sorry, I have not investigated the problem deeply yet.

**Comment by monagai** [comment]
Sorry, I might misunderstand something.
I will close it.
