### ISSUE TITLE
VAF question

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#105]
Hi,
Congrats on your recent pre-prints on targeted Nanoseq. We saw it described an unbiased BAM VAF. Is this calculated by the Nanoseq pipeline?

If not, do you all calculate it specifically from the BAM file created by randomreadinbundle?

And if so, how do you exclude the 'calling read' bundles? Does that exclusion mean that you exclude all the bundles that passed Nanoseq filters and available for mutation calling?

And then after this filtration, how is the VAF then extracted (bcftools mpileup?, any recommended filters on base quality/etc)?

Thanks!

**Comment by fa8sanger** [comment]
Hi,

Thank you.
Within the sequencing data there are two independent sets of reads: those with duplex coverage (2+2) and those without it. We call mutations in the first, hence we can explore the second to obtain unbiased VAFs. There may be some dependence between the two sets of reads (e.g. PCR errors at UMI barcodes) but independence is a very reasonable assumption.

From the deduplicated bam file we obtain the number of reads supporting the variant (numerator) and the total number of reads (denominator). This gives the bam vafs.

To calculate unbiased VAFs: The number of read bundles (or the duplex coverage) per site can be found in the cov.bed.gz file. We subtract this from the denominator.
The number of times a mutation has been called at a site can be found in the VCF. Subtract this from the numerator.

The script snv_merge_and_vaf_calc.R calculates duplex and bam vafs. It uses deepSNV::bam2R. Calculating unbiased vafs from these results is trivial as the script calculates all the necessary numbers.

Base qualities are tricky. The script provides bam vafs at bq10 and bq30. We usually work with bq30.

bam2R params:
q = 30, mask = 3844, mq = 30
q = 10, mask = 3844, mq = 30

An advantage of bam2R compared to other methods is that it properly handles overlaps between read pairs, avoiding double counting.

Fede


On 11 Nov 2024, at 20:29, gevro ***@***.***> wrote:



Hi,
Congrats on your recent pre-prints on targeted Nanoseq. We saw it described an unbiased BAM VAF. Is this calculated by the Nanoseq pipeline?

If not, do you all calculate it specifically from the BAM file created by randomreadinbundle?

And if so, how do you exclude the 'calling read' bundles? Does that exclusion mean that you exclude all the bundles that passed Nanoseq filters and available for mutation calling?

And then after this filtration, how is the VAF then extracted (bcftools mpileup?, any recommended filters on base quality/etc)?

Thanks!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_105&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=HbPu780ksAANVLUn9Zhy6e248CA1HqowOPFxPtthG3CP62sQ68QayvxjhCOq8BfH&s=owJ4KDcj8ASv9GL2ev9uOoZWIeyrxeQ94VD45k2KKJE&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3N2E5UBQRKEYHWPDPL2AEHTNAVCNFSM6AAAAABRSSJVTOVHI2DSMVQWIX3LMV43ASLTON2WKOZSGY2TAMZSGE4DENI&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=HbPu780ksAANVLUn9Zhy6e248CA1HqowOPFxPtthG3CP62sQ68QayvxjhCOq8BfH&s=JAjLXDBnHGD0pnmdI7nEk_9ekxt8N_vZs1eQ4I6OrBY&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by gevro** [comment]
Thanks! So can unbiased VAF be calculated using only the output of script snv_merge_and_vaf_calc.R ?

Specifically, would it be calculated like this from the VCF fields:
( BAM_MUT - TIMES_CALLED ) / ( BAM_COV - DUPLEX_COV )  ?

Or is unbiased VAF already calculated as one of the fields in the VCF?

**Comment by fa8sanger** [comment]
yes, we did everything handling overlaps correctly. And yes, you can calculate the unbiased vaf with that formula

On 12 Nov 2024, at 22:22, gevro ***@***.***> wrote:



Also, you mentioned that issue of avoiding double counting when the paired reads are overlapping. Does the above script also take that into account for the duplex mutation read counts that need to be subtracted from the numerator and does the cov.bed.gz take that into account since that number is subtracted from the denominator?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_105-23issuecomment-2D2471703393&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=vdns_jaoD2R_BrJhPdwZ4DfDKIiKVMIT6tiTW6ttzfdWObwReHJSBBK5ekwHcYes&s=BuUgiUUuHuPPuQ6kGY3z8rfQf5Qjna5mIjrhw8kNMoU&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3KGEY42IRAB2PRWA3L2AJ5Q7AVCNFSM6AAAAABRSSJVTOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINZRG4YDGMZZGM&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=vdns_jaoD2R_BrJhPdwZ4DfDKIiKVMIT6tiTW6ttzfdWObwReHJSBBK5ekwHcYes&s=XaZaith7Fnv6Dqs3iV3HuEXMC1dOrgV6eLWmzpLPPxI&e=>.
You are receiving this because you commented.Message ID: ***@***.***>


----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by gevro** [comment]
I'm curious - does the unbiased VAF take into account somehow the higher sequencing error when analyzing non-duplex read bundles?

**Comment by gevro** [comment]
Also: for targeted high-depth NanoSeq, since it is feasible to filter out germline variants based on their VAF in the targeted Nanoseq data-- without a separate matched germline sample, practically, how is the NanoSeq pipeline run without a matched germline sample? Do you run the pipeline by setting the germline sample to be the neat BAM file of the targeted Nanoseq somatic sample?

Or is a totally separate matched germline still required for fully accurate results as it is for non-targeted NanoSeq?

**Comment by fa8sanger** [comment]
You can use the same sample as its own matched normal. Just provide the deduplicated bam as the matched normal. Since somatic mutations will be observed in the matched normal you would need to relax the vaf threshold and increase the minimum required matched normal coverage.
Of course this strategy only works if your sample is polyclonal


On 3 Dec 2024, at 03:16, gevro ***@***.***> wrote:



Also: for targeted high-depth NanoSeq, since it is feasible to filter out germline variants based on their VAF in the targeted Nanoseq data-- without a separate matched germline sample, practically, how is the NanoSeq pipeline run without a matched germline sample? Do you run the pipeline by setting the germline sample to be the neat BAM file of the targeted Nanoseq somatic sample?

Or is a totally separate matched germline still required for fully accurate results as it is for non-targeted NanoSeq?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_105-23issuecomment-2D2513459317&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=PWR2K9vngz6vPO6BplXCnTTTzQ8IxZ25xvxNMgc63ZLjIdX9zNvtHj6V1LxH5-go&s=RgUpOCtJTPdPJ7PU0ag0C9lcGj1UgoI2Qsihzhsg018&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3KKBX4OXKCVSVLVDQT2DUO7ZAVCNFSM6AAAAABRSSJVTOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMJTGQ2TSMZRG4&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=PWR2K9vngz6vPO6BplXCnTTTzQ8IxZ25xvxNMgc63ZLjIdX9zNvtHj6V1LxH5-go&s=F3micxnyN9j224mPwYlNltkUXE3CaEdM_hveUMC3mts&e=>.
You are receiving this because you commented.Message ID: ***@***.***>


----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.

**Comment by gevro** [comment]
I realized I don't fully understand why unbiased BAM VAFs (which only use data from non-2+2 read bundles) provides a more accurate estimate of the fraction of reads with a specific mutation, as opposed to just using the BAM VAF fields (BAM_MUT / BAM_COV) that includes both 2+2 read bundles and non-2+2 read bundles.

If we count detection in each read bundle only once, including all types of read bundles, then I don't follow why this wouldn't provide a better estimate than only looking at non-2+2 read bundles. This estimate would use all read bundles without any filtering specific to the read bundle type, and it would provide higher coverage.

Thanks for explaining this!

**Comment by fa8sanger** [comment]
The idea is to do a sort of replication experiment, like an independent sequencing. What would you see if you sequence again the sample?

On 5 Dec 2024, at 23:12, gevro ***@***.***> wrote:



I realized I don't fully understand why unbiased BAM VAFs (which only use data from non-2+2 read bundles) provides a more accurate estimate of the fraction of reads with a specific mutation, as opposed to just using the BAM VAF fields (BAM_MUT / BAM_COV) that includes both 2+2 read bundles and non-2+2 read bundles.

If we count detection in each read bundle only once, including all types of read bundles, then I don't follow why this wouldn't provide a better estimate than only looking at non-2+2 read bundles. This estimate would use all read bundles without any filtering specific to the read bundle type, and it would provide higher coverage.

Thanks for explaining this!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_105-23issuecomment-2D2521694207&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=aej2hW3FkLXnwGqKjI5mOfvtu5YeGd6EXA-ZGeSjIcxbUsodMWU_5GljaP82_FRB&s=KPyFNYvsvFUvTCuNVHHr0urf7NdnZMc8D0qWlgjNbCE&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3OYV3BBTZLUQHXD47D2EDMXNAVCNFSM6AAAAABRSSJVTOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRRGY4TIMRQG4&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=aej2hW3FkLXnwGqKjI5mOfvtu5YeGd6EXA-ZGeSjIcxbUsodMWU_5GljaP82_FRB&s=bKKuPpkWG98ZOb0Cx-erudtUD2GB3_Q8WzyCkrOQcuk&e=>.
You are receiving this because you commented.Message ID: ***@***.***>


----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.
