### ISSUE TITLE
Optimal efficiency and optimizing efficiency

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#21]
Hi,
I have two questions regarding interpretation of the Efficiency QC:
1) Your README on github says:
"EFFICIENCY: This is the number of duplex bases divided by the number of sequenced bases. Efficiency is maximised to ~0.07 when duplicate rates and strand drop outs are optimal"

However, Extended Data Fig. 4A of the paper in Nature, middle panel, shows that maximum analytical efficiency is ~0.12, and the maximum observed efficiency is 0.04 in Extended Fig. 4D.

What is the maximal/optimal efficiency: 0.04 or 0.07?

2) If EFFICIENCY and DUPLICATE_RATE are too low relative to the optimum, do you recommend optimizing based on EFFICIENCY or based on DUPLICATE_RATE when deciding how much less fmol library to input into the final PCR?
 - For example, given EFFICIENCY = 0.02 and DUPLICATE_RATE = 0.49, how much less fmol input should be added to the final PCR for the same total sequencing coverage? Optimizing based on EFFICIENCY or based on DUPLICATE_RATE will lead to different decisions.
 - Furthermore, Extended Data Fig. 4A shows DUPLICATE_RATE vs sequencing reads/fmol library, which could be used to do this estimation, but if optimizing based on EFFICIENCY is better, the relationship of EFFICIENCY vs sequencing reads/fmol library is not clear. 

Thanks.

**Comment by fa8sanger** [comment]
Hi Gevro,

1. In theory, efficiency is maximised at 81% duplicate rate but in practice it is maximised at ~76%. Duplicate rate is the main parameter affecting efficiency but others such as DNA damage can have an impact. The strand drop out (F-EFF) can give you insights on DNA damage. There may be other factors affecting efficiency such as DNA denaturation before dilution or strong PCR biases. In Ext Data Fig 4d you have the empirical duplicate rate - efficiency, after applying all the filters, which is maximised at 0.04. Before applying filters its maximum is 0.07 (as stated in the README). In other words, you should work on duplicate rates to optimise efficiency, with other factors potentially reducing the 0.07 maximum but not altering the optimal duplicate rates.

2. If you obtain 0.49 duplicate rates, looking at the first panel in Ext Data Fig 4a I would say you need to double your sequencing or halve your input fmols to get closer to 81% duplicate rates. Looking at the methods section "Library dilution and sequencing efficiency” you can work out the dilution to achieve r=5.1. The formula fmol(opt)= N / f * r(opt) is what you need. In our hands we estimated f to be 1e8 fragments per fmol but that may vary depending on your DNA quantification. But as I said, doubling the coverage (or halving the complexity) would get you close to the optimum.

Playing with d=1-(1-exp(-r))/r can help too. But remember that the analytical values are not the same as the empirical. I estimated that if you double the coverage your 0.49 duplicate rate would turn into 0.68, very close to the optimum.

Best,
Fede


On 1 Jan 2022, at 07:21, gevro ***@***.******@***.***>> wrote:



Hi,
I have two questions regarding interpretation of the Efficiency QC:

  1.  Your README on github says:
"EFFICIENCY: This is the number of duplex bases divided by the number of sequenced bases. Efficiency is maximised to ~0.07 when duplicate rates and strand drop outs are optimal"

However, Extended Data Fig. 4A of the paper in Nature, middle panel, shows that maximum efficiency is ~0.12.

What is the maximal/optimal efficiency: 0.07 or 0.12?

  1.  If EFFICIENCY and DUPLICATE_RATE are too low relative to the optimum, do you recommend optimizing based on EFFICIENCY or based on DUPLICATE_RATE when deciding how much less fmol library to input into the final PCR?

  *   For example, given EFFICIENCY = 0.02 and DUPLICATE_RATE = 0.49, how much less fmol input should be added to the final PCR for the same total sequencing coverage? Optimizing based on EFFICIENCY or based on DUPLICATE_RATE will lead to different decisions.
  *   Furthermore, Extended Data Fig. 4A shows DUPLICATE_RATE vs sequencing reads/fmol library, which could be used to do this estimation, but if optimizing based on EFFICIENCY is better, the relationship of EFFICIENCY vs sequencing reads/fmol library is not clear.

Thanks.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_21&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=iIJhrz3nyKRDSpCiLGEGyPqVm2IoUH4KvMOgAXHVxceMvNt_SvP0OzaydAtla-7u&s=2j1HbWWBsn5tJztrbViz_S7f5-zSafB77BZ1WVQVZ9E&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3MEIXGR7LVNF7IYKYTUT2TRLANCNFSM5LCGSFMQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=iIJhrz3nyKRDSpCiLGEGyPqVm2IoUH4KvMOgAXHVxceMvNt_SvP0OzaydAtla-7u&s=7r8L8FKOzFFMrXduDtzWz_lFKjGkQQ_dFyp-ZGTBTRo&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=iIJhrz3nyKRDSpCiLGEGyPqVm2IoUH4KvMOgAXHVxceMvNt_SvP0OzaydAtla-7u&s=WX_YZoDnZqd_QUrNLb2lqzKvthQqo0FetXPYV-gY-sA&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=iIJhrz3nyKRDSpCiLGEGyPqVm2IoUH4KvMOgAXHVxceMvNt_SvP0OzaydAtla-7u&s=8lpx2JW9UjrtyKTzpDU6EP2goZk_lmS7qJIkQVXgrFU&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thank you! This is really helpful.
