### ISSUE TITLE
Number of PCR cycles in the protocol

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#22]
Hi,
I realized I'm not clear on the # of PCR cycles in the protocol:
https://protocolexchange.researchsquare.com/article/pex-1298/v1 says "Step 4: Return to Step 2, X times"

And then it says: "The number of PCR cycles is dependent upon the input: 0.1 fmol (0.066 fmol) = 16 cycles, 0.3 fmol (0.2 fmol) = 14 cycles, 0.6 fmol (0.4 fmol) = 13 cycles, 5 fmol (3.33 fmol) = 10 cycles. "

"The number of PCR cycles": Does that refer to "X" in "X times", or does that refer to the total number of cycles, i.e. "The number of PCR cycles" = X-1?

Also, if we by mistake did 1 extra PCR cycle, am I correct that this should not theoretically affect any of the efficiency/duplication rate/etc results?

**Comment by fa8sanger** [comment]
Hi gevro,

cc’ing Stef in case I say something wrong (she’s the lab expert).

I am pretty sure the X is the number of PCR cycles. I don’t think an extra cycle would have much of an impact.

Best,
Fede



On 3 Jan 2022, at 02:16, gevro ***@***.******@***.***>> wrote:



Hi,
I realized I'm not clear on the # of PCR cycles in the protocol:
https://protocolexchange.researchsquare.com/article/pex-1298/v1 [protocolexchange.researchsquare.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__protocolexchange.researchsquare.com_article_pex-2D1298_v1&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=sGHflSLqT3Lm3qmr5ujcYn5TEbf79q9RmlmNN4sfXN2lnjOccVDAIqRFbXYdAGdQ&s=GjBtSk9RmFKTgp7xQUHcrShhjWiJe0V-ZpiGUYYQdK4&e=> says "Step 4: Return to Step 2, X times"

And then it says: "The number of PCR cycles is dependent upon the input: 0.1 fmol (0.066 fmol) = 16 cycles, 0.3 fmol (0.2 fmol) = 14 cycles, 0.6 fmol (0.4 fmol) = 13 cycles, 5 fmol (3.33 fmol) = 10 cycles. "

"The number of PCR cycles": Does that refer to "X" in "X times", or does that refer to the total number of cycles, i.e. "The number of PCR cycles" = X-1?

Also, if we by mistake did 1 extra PCR cycle, am I correct that this should not theoretically affect any of the efficiency/duplication rate/etc results?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_22&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=sGHflSLqT3Lm3qmr5ujcYn5TEbf79q9RmlmNN4sfXN2lnjOccVDAIqRFbXYdAGdQ&s=qM7PoPfz-QCal4zfi80oM0o8pGEs2hLEk-wU7HitwlI&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3IAYN3VWAR2Y7IZ3XLUUEBGDANCNFSM5LELGR6Q&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=sGHflSLqT3Lm3qmr5ujcYn5TEbf79q9RmlmNN4sfXN2lnjOccVDAIqRFbXYdAGdQ&s=6U4r9eU-DIxiqh-WlxfOIWbtbyw5T7eNQRt7l-ka6uo&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=sGHflSLqT3Lm3qmr5ujcYn5TEbf79q9RmlmNN4sfXN2lnjOccVDAIqRFbXYdAGdQ&s=VCPG_VF_qsK9XALK-uuj5mIXJ9fp18MbTONlJ-g7A6M&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=sGHflSLqT3Lm3qmr5ujcYn5TEbf79q9RmlmNN4sfXN2lnjOccVDAIqRFbXYdAGdQ&s=dMSR_ZMYFbgWHij4iErDqZqHbqjr7FbWw3zTSU6bGIo&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by fa8sanger** [comment]
Hi Gevro,

E.g. for 0.3 fmol (0.2 fmol)  we recommend  14  total cycles.
So when returning to step 2, X times – you would return 13 times to achieve 14 total cycles.
However, these cycles are just a guide – doing slightly more or less will not change the outcome.

Best wishes,
Stef

From: Federico Abascal ***@***.***>
Date: Tuesday, 4 January 2022 at 15:52
To: cancerit/NanoSeq ***@***.***>
Cc: Stefanie Lensing ***@***.***>
Subject: Re: [cancerit/NanoSeq] Number of PCR cycles in the protocol (Issue #22) [EXT]

Hi gevro,

cc’ing Stef in case I say something wrong (she’s the lab expert).

I am pretty sure the X is the number of PCR cycles. I don’t think an extra cycle would have much of an impact.

Best,
Fede




On 3 Jan 2022, at 02:16, gevro ***@***.******@***.***>> wrote:


Hi,
I realized I'm not clear on the # of PCR cycles in the protocol:
https://protocolexchange.researchsquare.com/article/pex-1298/v1 [protocolexchange.researchsquare.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__protocolexchange.researchsquare.com_article_pex-2D1298_v1&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=sGHflSLqT3Lm3qmr5ujcYn5TEbf79q9RmlmNN4sfXN2lnjOccVDAIqRFbXYdAGdQ&s=GjBtSk9RmFKTgp7xQUHcrShhjWiJe0V-ZpiGUYYQdK4&e=> says "Step 4: Return to Step 2, X times"
And then it says: "The number of PCR cycles is dependent upon the input: 0.1 fmol (0.066 fmol) = 16 cycles, 0.3 fmol (0.2 fmol) = 14 cycles, 0.6 fmol (0.4 fmol) = 13 cycles, 5 fmol (3.33 fmol) = 10 cycles. "
"The number of PCR cycles": Does that refer to "X" in "X times", or does that refer to the total number of cycles, i.e. "The number of PCR cycles" = X-1?
Also, if we by mistake did 1 extra PCR cycle, am I correct that this should not theoretically affect any of the efficiency/duplication rate/etc results?
—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_22&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=sGHflSLqT3Lm3qmr5ujcYn5TEbf79q9RmlmNN4sfXN2lnjOccVDAIqRFbXYdAGdQ&s=qM7PoPfz-QCal4zfi80oM0o8pGEs2hLEk-wU7HitwlI&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3IAYN3VWAR2Y7IZ3XLUUEBGDANCNFSM5LELGR6Q&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=sGHflSLqT3Lm3qmr5ujcYn5TEbf79q9RmlmNN4sfXN2lnjOccVDAIqRFbXYdAGdQ&s=6U4r9eU-DIxiqh-WlxfOIWbtbyw5T7eNQRt7l-ka6uo&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=sGHflSLqT3Lm3qmr5ujcYn5TEbf79q9RmlmNN4sfXN2lnjOccVDAIqRFbXYdAGdQ&s=VCPG_VF_qsK9XALK-uuj5mIXJ9fp18MbTONlJ-g7A6M&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=sGHflSLqT3Lm3qmr5ujcYn5TEbf79q9RmlmNN4sfXN2lnjOccVDAIqRFbXYdAGdQ&s=dMSR_ZMYFbgWHij4iErDqZqHbqjr7FbWw3zTSU6bGIo&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thank you!
