### ISSUE TITLE
Settings for running pipeline

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#24]
Hi,
I noticed some differences between the settings you recommend here on github and in the bjobGen.sh script versus the paper. For example:
 - The paper says, "We require that each read bundle (that is, group of PCR duplicates) has at least two reads from each of the two original DNA strands." But runNanoSeq.py var -b  = 5 (minimum duplex reads per strand)
 - The paper says "The matched normal must have ≥15× coverage at a given site to make the risk of undetected heterozygous SNPs negligible.". But runNanoSeq.py var -z = 12 (minimum total number of normal reads)

There may be other discrepancies in addition to these, but it is difficult to match up text from the paper with the exact pipeline settings, so I am not sure.

Can you clarify the best settings to use?

Thanks!

**Comment by fa8sanger** [comment]
Sorry about this, the help has an error. That’s the coverage in the matched normal per strand. The parameter -z controls the minimum total depth in the matched normal, the parameter -b the minimum number of reads in each orientation. If the matched normal is standard sequencing I usually set -b to 1 or 2 and -z either to 12 or 15. If the coverage in the matched normal is high enough, using -z 15 would be safer against leaking SNPs.

You can leave the other options as default.

@Raúl, we need to correct the description of parameter “-b”

Fede


On 23 Jan 2022, at 03:40, gevro ***@***.******@***.***>> wrote:



Hi,
I noticed some differences between the settings you recommend here on github and in the bjobGen.sh script versus the paper. For example:

  *   The paper says, "We require that each read bundle (that is, group of PCR duplicates) has at least two reads from each of the two original DNA strands." But runNanoSeq.py var -b = 5 (minimum duplex reads per strand)
  *   The paper says "The matched normal must have ≥15× coverage at a given site to make the risk of undetected heterozygous SNPs negligible.". But runNanoSeq.py var -z = 12 (minimum total number of normal reads)

There may be other discrepancies in addition to these, but it is difficult to match up text from the paper with the exact pipeline settings, so I am not sure.

Can you clarify the best settings to use?

Thanks!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_24&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=9OZXTmuGWc_BoCuCxEV3ZiWJulR5sRLIDJtxS0uIpoDbk2MQxE51edEHeL8kMaAR&s=FWnUmZxw-oKbd5qzVSYYxIS6oOTAdi_XqKMzoVDWQdk&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3IBZ6XHKL2V5WJGYP3UXN2CHANCNFSM5MSZ7L7A&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=9OZXTmuGWc_BoCuCxEV3ZiWJulR5sRLIDJtxS0uIpoDbk2MQxE51edEHeL8kMaAR&s=YlwPZw5n74uqgyDulzdOd5wBhJtyfkUXuFAc5jezvV0&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=9OZXTmuGWc_BoCuCxEV3ZiWJulR5sRLIDJtxS0uIpoDbk2MQxE51edEHeL8kMaAR&s=CUNxR22WSsQa-OWnQtZXv43NKNG3I4xuvSxO7KatOew&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=9OZXTmuGWc_BoCuCxEV3ZiWJulR5sRLIDJtxS0uIpoDbk2MQxE51edEHeL8kMaAR&s=4vcRimR-rF1WPeOSQwweGrjLYWEg-2UWXIH4NC62BwQ&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thanks. However, if -b is the # of reads per strand orientation in matched normal, -b 1 or 2 seems too low to me. Shouldn't it be -b 5 ?

**Comment by fa8sanger** [comment]
With -b > 0 you require that there is at least 1 read per each orientation. Some problematic regions can be detected because most reads map in an unique orientation. But feel free to play with the parameters.

On 23 Jan 2022, at 21:47, gevro ***@***.******@***.***>> wrote:



Thanks. However, if -b is the # of reads per strand orientation in matched normal, -b 1 or 2 seems too low to me. Shouldn't it be -b 5 ?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_24-23issuecomment-2D1019573911&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=kkniDUij54hXGGuELAVAqnKI-xTdxlUgTMSssBdmkG8vGAcmX9POnlu67Nas9uxl&s=uhashPdN97hAKtsks5He-Jb7MhHTGGY5Lvkq_7cfyEY&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3LWW7V7SNKSFP6ZE3TUXRZPXANCNFSM5MSZ7L7A&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=kkniDUij54hXGGuELAVAqnKI-xTdxlUgTMSssBdmkG8vGAcmX9POnlu67Nas9uxl&s=X7H9PgvjVlxKtmEy1g3FY8UINgGM29i4jHHllDcJHFU&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=kkniDUij54hXGGuELAVAqnKI-xTdxlUgTMSssBdmkG8vGAcmX9POnlu67Nas9uxl&s=Vn8cZyQISboLcSUfqwqsUqTd0FoqTLAE-EA0vIOniSs&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=kkniDUij54hXGGuELAVAqnKI-xTdxlUgTMSssBdmkG8vGAcmX9POnlu67Nas9uxl&s=LYnn9pbXz9hRQEcQ7zBOLt041lhUG-P-VVyVlG0XpLI&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Ok

**Comment by gevro** [comment]
I realize I am not clear about -b. Is that the minimum number of reads per orientation in matched normal in order to exclude the variant?

In other words, does reducing -b from 5 to 1 or 2 cause more somatic mutations to be filtered out because more sites in the matched normal will be considered as germline sites?

**Comment by fa8sanger** [comment]
No, the frequency is controlled by -v. The depth in the matched normal is controlled by -z (total depth) and -b (strand depth). Requiring to have at least some reads covering both orientations is an effective filter against problematic regions. Does that make sense?




On 26 Jan 2022, at 15:05, gevro ***@***.******@***.***>> wrote:



I realize I am not clear about -b. Is that the minimum number of reads per orientation in matched normal in order to exclude the variant?

In other words, does reducing -b from 5 to 1 or 2 cause more somatic mutations to be filtered out because more sites in the matched normal will be considered as germline sites?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_24-23issuecomment-2D1022285109&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=XZL3bNQUI5ym_VCLHXz3lepZ_ZK0Wu9BoUNwx2wNF_SxAw9hXwlrt9v23DYm6XrP&s=5cr8EB_2Wfy1wLZRowDDftoZqqzR3mxJbUmMOEfkJ3A&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3PCXRTPUBRNEUFKJTDUYAEUDANCNFSM5MSZ7L7A&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=XZL3bNQUI5ym_VCLHXz3lepZ_ZK0Wu9BoUNwx2wNF_SxAw9hXwlrt9v23DYm6XrP&s=w8-dW1dweHBfQ8Kp8nZdNQrpseFWEOQt8t5YdNTyczc&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=XZL3bNQUI5ym_VCLHXz3lepZ_ZK0Wu9BoUNwx2wNF_SxAw9hXwlrt9v23DYm6XrP&s=on42YMGA2hLoGGwqZoEfDLy597qOhVQwFwT9IYDDD2c&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=XZL3bNQUI5ym_VCLHXz3lepZ_ZK0Wu9BoUNwx2wNF_SxAw9hXwlrt9v23DYm6XrP&s=PeCT1x_oTWIMBZ-kucgb7YCpbmFxIOtwbt7MfvDHtzA&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
I'm not sure I understand. Can you clarify the definition of -b more precisely?

Here are some questions I am unsure about:
1) Does -b apply to the matched normal or to the Nanoseq somatic BAM reads?
2) Is -b a filter on strand orientation?
3) Is it the minimum number of reads per strand orientation for somatic variants, or for germline variants for filtering?

For example, if -b is the mininum # of reads per orientation in the matched normal for calling germline variants, does that mean that lower -b will reduce the chance of false positive somatic variants, because it have a lower threshold for considering a site as germline in the matched normal?

**Comment by fa8sanger** [comment]
-b is the minimum number of reads covering each strand in the matched normal. The matched normal is used to identify germline variants + problematic regions.

while -v/ -z are used to detect germline, -b is aimed at flagging problematic regions, regions where all reads map in a single orientation.

-b has to be 0 for neat normals (nanoseq undiluted libraries), but it works well in that case. As I said, feel free to play with -b.

On 26 Jan 2022, at 17:01, gevro ***@***.******@***.***>> wrote:



I'm not sure I understand. Can you clarify the definition of -b more precisely?

Here are some questions I am unsure about:

  1.  Does -b apply to the matched normal or to the Nanoseq somatic BAM reads?
  2.  Is -b a filter on strand orientation?
  3.  Is it the minimum number of reads per strand orientation for somatic variants, or for germline variants for filtering?

For example, if -b is the mininum # of reads per orientation in the matched normal for calling germline variants, does that mean that lower -b will reduce the chance of false positive somatic variants, because it have a lower threshold for considering a site as germline in the matched normal?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_24-23issuecomment-2D1022399188&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=03h5PDv2t10zxMAO54XTn07GZr8lXa16zfMR2U_XkGjnKIgIWnV6i-tAsz6EurAv&s=rljm_gGaBBjzgTxLb2XPLFfPewZEV3CC4i5oAxDyMG4&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3NCIUNIVEAHNA4ZG4TUYASFHANCNFSM5MSZ7L7A&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=03h5PDv2t10zxMAO54XTn07GZr8lXa16zfMR2U_XkGjnKIgIWnV6i-tAsz6EurAv&s=lnAwjmCTMWBBF__gnVoEHllRqRbekCi7xrYJk08CzCo&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=03h5PDv2t10zxMAO54XTn07GZr8lXa16zfMR2U_XkGjnKIgIWnV6i-tAsz6EurAv&s=DQAuzRzu23Kdt_JT0skY1txf70xa_BYRyvBb8_l0vMU&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=03h5PDv2t10zxMAO54XTn07GZr8lXa16zfMR2U_XkGjnKIgIWnV6i-tAsz6EurAv&s=8ydYwzEA8zWmaKkmDc2ostYeZNStLt8sNxxvf-2AabE&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Oh ok. I think I understand now:
var -b requires a minimum number of reads in each orientation in the matched normal to even consider the region in the analysis. So higher -b reduces regions prome to false positives, but reduces number of duplex bp considered.
-> Is that correct?

Two follow up questions:
1) Regarding -b equal to 0 for undiluted nanoseq normal— Shouldn’t undiluted nanoseq neat normal still have reads in both orientations? Why would -b be different for the two types of matched normal?

2) Are the any other settings in the pipeline that should be different between standard WGS matched normal versus undiluted nanoseq matched normal?

Thank you!

**Comment by fa8sanger** [comment]
You got it!

1. When you do restriction enzyme digestion you don’t get that diversity in mapping orientations. This snapshop of IGV for standard vs neat shows it visually:

2. Nope


On 26 Jan 2022, at 17:22, gevro ***@***.******@***.***>> wrote:



Oh ok. I think I understand now:
var -b requires a minimum number of reads in each orientation in the matched normal to even consider the region in the analysis. So higher -b reduces regions prome to false positives, but reduces number of duplex bp considered.
-> Is that correct?

Two follow up questions:

  1.  Regarding -b equal to 0 for undiluted nanoseq normal— Shouldn’t undiluted nanoseq neat normal still have reads in both orientations? Why would -b be different for the two types of matched normal?

  2.  Are the any other settings in the pipeline that should be different between standard WGS matched normal versus undiluted nanoseq matched normal?

Thank you!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_24-23issuecomment-2D1022419239&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=HBKNGCT0wtu2OwisRiZnbObN__0IkBCy_CzSA4y9qTfCA7bEbpK--x0MYzQWE6OF&s=VbmLHn2UYYyp5w3XZcmtxsfkBUObbipe5NkXPZe8yd0&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3PS62MIJIWFOEQVQSLUYAUUVANCNFSM5MSZ7L7A&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=HBKNGCT0wtu2OwisRiZnbObN__0IkBCy_CzSA4y9qTfCA7bEbpK--x0MYzQWE6OF&s=rrvIlC25bJgoJN58A_B4KYLUUR197fNuKTU1em5BwM0&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=HBKNGCT0wtu2OwisRiZnbObN__0IkBCy_CzSA4y9qTfCA7bEbpK--x0MYzQWE6OF&s=5qU-_eCw2fpyiee-uc4aO-BQ1tUwXJhcDRCaBTlX9Bg&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=HBKNGCT0wtu2OwisRiZnbObN__0IkBCy_CzSA4y9qTfCA7bEbpK--x0MYzQWE6OF&s=3ndoR6Ls7BogYmRdW8qCJjtId9cvXniJ1JDWRR6OKkA&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thank you! Are you able to reattach the screenshot? It didn’t come through on the GitHub website.

**Comment by fa8sanger** [comment]
trying again…

[cid:DB1BFACA-9BFD-474B-8C2E-E6EBD189D35B]

On 26 Jan 2022, at 17:37, gevro ***@***.******@***.***>> wrote:



Thank you! Are you able to reattach the screenshot? It didn’t come through on the GitHub website.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_24-23issuecomment-2D1022432253&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=hKYC6a1omIL_qvyc-NW7jUGIUcK0MJvudSO0ZqUctundjfIIzDTCuIoU0OpvzfS8&s=FsBviG18Q3hL5G3R47HhOMxtjtlpOQMw5UR1iHOXs-c&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3JIXTCK5PELLXYALJDUYAWNJANCNFSM5MSZ7L7A&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=hKYC6a1omIL_qvyc-NW7jUGIUcK0MJvudSO0ZqUctundjfIIzDTCuIoU0OpvzfS8&s=3l7l_T8VZ0D07Is_v5Mi18dkHNtCrsN3v6BMVhjMBGo&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=hKYC6a1omIL_qvyc-NW7jUGIUcK0MJvudSO0ZqUctundjfIIzDTCuIoU0OpvzfS8&s=BkrEosCWYn-vTG-zNu90jO4wMcHsQO733TRGmF9A8mg&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMFaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=hKYC6a1omIL_qvyc-NW7jUGIUcK0MJvudSO0ZqUctundjfIIzDTCuIoU0OpvzfS8&s=TqM8fTnsBU5oI0_8s9C3O0ywXx49TExRA_O9e6VL0o0&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Sorry, still not appearing.

**Comment by fa8sanger** [comment]
don’t know how to send it, if you send me your email address I can email it

On 26 Jan 2022, at 18:41, gevro ***@***.******@***.***>> wrote:



Sorry, still not appearing.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_24-23issuecomment-2D1022485002&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=KM7BAyoOZeZlgC0XcfyVZTzMKWm6rYo5k8v1Zkw_c03uScu2kAohOWYI0Z7iA_jR&s=a8SX6OrWSDf3PtBUj51667QsjeyrdwvfJbU1ZwUFP_0&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3NMKZT3WR6GAQFQSRLUYA55HANCNFSM5MSZ7L7A&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=KM7BAyoOZeZlgC0XcfyVZTzMKWm6rYo5k8v1Zkw_c03uScu2kAohOWYI0Z7iA_jR&s=qgfBSCoMlXfeoHqPIiYAdKJ0xkLW3N0SveJ5OAtrPSA&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=KM7BAyoOZeZlgC0XcfyVZTzMKWm6rYo5k8v1Zkw_c03uScu2kAohOWYI0Z7iA_jR&s=l2S9unnkhGSE9jhIBrbEnmZCsj9y2EhBmtAxAkwt8dM&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=KM7BAyoOZeZlgC0XcfyVZTzMKWm6rYo5k8v1Zkw_c03uScu2kAohOWYI0Z7iA_jR&s=KIA2n_WWqc07KG7ZCB2HlM7hLOBgRGYgqei8N9KruZ4&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
