### ISSUE TITLE
Matched normal that is not a nanoseq library

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#25]
Hi,
What is the pre-processing necessary for a matched normal that is *not* a nanoseq library? Specifically, is it sufficient to simply mark PCR/optical duplicates, or do they need to be filtered?

Thanks.

**Comment by fa8sanger** [comment]
They don’t need a particular processing other than marking duplicates and being in the same chromosome order as the nanoseq bam. If still the pipeline is giving you errors about the pre-processing you can try running with option no_test in runNanoSeq.py , but that may be risky if there are problems that need fixing


On 23 Jan 2022, at 19:52, gevro ***@***.******@***.***>> wrote:



Hi,
What is the pre-processing necessary for a matched normal that is not a nanoseq library? Specifically, is it sufficient to simply mark PCR/optical duplicates, or do they need to be filtered?

Thanks.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_25&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=mJZqRQnnfqGuD_cX7XNiW53Kd-seJrja9_tNwtRUhjGZrcsC-0HUbQw-RpXkWAzc&s=TGzGiWmJx3fkfABVBW3sEtK-q1BunW-rMh4GL6vN5X8&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3KIK5XNQ3UEGQPF4ETUXRMAZANCNFSM5MTXVWWQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=mJZqRQnnfqGuD_cX7XNiW53Kd-seJrja9_tNwtRUhjGZrcsC-0HUbQw-RpXkWAzc&s=7DkShoVe_Nzo26dcGtb-imI2gFELMJahOheu57wuiYk&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=mJZqRQnnfqGuD_cX7XNiW53Kd-seJrja9_tNwtRUhjGZrcsC-0HUbQw-RpXkWAzc&s=cQmG4ajCPxQr9pwPKFZXHOm6C-OvxjLYGSNNBdZwQVU&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=mJZqRQnnfqGuD_cX7XNiW53Kd-seJrja9_tNwtRUhjGZrcsC-0HUbQw-RpXkWAzc&s=23GJXUY8xZyF7cpp1D6hj9DcRQDGHTd6cpp3EQtfxuE&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thanks. Follow-up question just to make sure I understand:
If using a Nanoseq non-diluted reference, the pipeline requires randomreadinbundle to be run on it first. However, is using a non-Nanoseq reference, does the downstream Nanoseq pipeline remove PCR/optical duplicates that are marked? Because there is no explicit step to do that, so this would need to be programmed into the pipeline.

If the downstream Nanoseq pipeline does not remove/filter PCR/optical duplicates of non-Nanoseq reference, should I then manually remove them?

**Comment by fa8sanger** [comment]
No need for that. If PCR duplicates are flagged, then the pipeline will ignore them. The reason we run randomreadinbundle is in part because we don’t have proper duplicate flagging implemented (it not only depends on mapping coordinates, also on barcodes as you probably know)



On 23 Jan 2022, at 21:50, gevro ***@***.******@***.***>> wrote:



Thanks. Follow-up question just to make sure I understand:
If using a Nanoseq non-diluted reference, the pipeline requires randomreadinbundle to be run on it first. However, is using a non-Nanoseq reference, does the downstream Nanoseq pipeline remove PCR/optical duplicates that are marked? Because there is no explicit step to do that, so this would need to be programmed into the pipeline.

If the downstream Nanoseq pipeline does not remove/filter PCR/optical duplicates of non-Nanoseq reference, should I then manually remove them?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_25-23issuecomment-2D1019574258&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=-lgub24B48zyDxVBJnvGgBMOQ32DZAnG-ol1FsZg-iLWrVGxQ5M8UDCAzVU0HmRU&s=CvSt1YNmPw9g8qihVEPCra-srlxjky1_bn5gRFMc2Us&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3LWSC3BCRYNDUBGIWDUXRZY7ANCNFSM5MTXVWWQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=-lgub24B48zyDxVBJnvGgBMOQ32DZAnG-ol1FsZg-iLWrVGxQ5M8UDCAzVU0HmRU&s=LxN_5bUb4TKF4o86UGQTN4TAN86o9n78_bbC23d7Ifs&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=-lgub24B48zyDxVBJnvGgBMOQ32DZAnG-ol1FsZg-iLWrVGxQ5M8UDCAzVU0HmRU&s=YZoWvxKtn1gHdGtPQx_RWmm5i-0RhrJnmUH7mMcpDeI&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=-lgub24B48zyDxVBJnvGgBMOQ32DZAnG-ol1FsZg-iLWrVGxQ5M8UDCAzVU0HmRU&s=XT6QzOz4o90-t69ropqPX3JnixL410akv7_lFatYLaw&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thank you!
