### ISSUE TITLE
--exclude option for runNanoseq.py cov

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#27]
Hi,
To exclude chromosomes, is the only setting --exclude for runNanoseq.py cov ?
Or do any other steps of the pipeline require settings to exclude specific chromosomes?

Thanks.

**Comment by fa8sanger** [comment]
That’s right. You can provide a list of chromosome within quotes, and use wildcard “%”.
Options --larger and --include may also be of interest

On 6 Feb 2022, at 20:43, gevro ***@***.******@***.***>> wrote:



Hi,
To exclude chromosomes, is the only setting --exclude for runNanoseq.py cov ?
Or do any other steps of the pipeline require settings to exclude specific chromosomes?

Thanks.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_27&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=7jOF9J9FS-ivrcglAR_v9Fu6-0wPvEAo4JKoRqTLpEVFLr6GKbHtxVLhXjGa3T6c&s=qoZ6aGjNKMYku8SRUjl6C70mZ35lJBussO1_IUxL_cc&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3NK6U2LE7I2TUX2NIDUZ3MPNANCNFSM5NVZOCEQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=7jOF9J9FS-ivrcglAR_v9Fu6-0wPvEAo4JKoRqTLpEVFLr6GKbHtxVLhXjGa3T6c&s=IzeH9BqyVLt3k2VOQulM69SWhIddSFhMr-KYdT809vY&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=7jOF9J9FS-ivrcglAR_v9Fu6-0wPvEAo4JKoRqTLpEVFLr6GKbHtxVLhXjGa3T6c&s=TN6esbeslFOyxEZdfgCoG77PJ6yEk_YQTlrlgJ8Rh70&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=7jOF9J9FS-ivrcglAR_v9Fu6-0wPvEAo4JKoRqTLpEVFLr6GKbHtxVLhXjGa3T6c&s=Xi3HmJ1h1PX63aImNk-j2QZCKtJaQ5see7C-KR7-Pc8&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
