### ISSUE TITLE
SNP and NOISE masks included in mutation rate calculations?

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#28]
In the README, it states "SNP and NOISE BED files contain sites to be marked on the output VCF file."

Does this mean that variant in sites of SNP and NOISE BED masks will be or will not be included in the final mutation rate calculations? i.e. are they only marked in the output VCF file but are still included in mutation rate calculations?

Thank you.

**Comment by fa8sanger** [comment]
Sites overlapping the SNP and NOISE masks are not used for the mutation rate calculations. However, they are provided in the final VCF file (those without the PASS flag)

On 6 Feb 2022, at 20:58, gevro ***@***.******@***.***>> wrote:



In the README, it states "SNP and NOISE BED files contain sites to be marked on the output VCF file."

Does this mean that variant in sites of SNP and NOISE BED masks will be or will not be included in the final mutation rate calculations? i.e. are they only marked in the output VCF file but are still included in mutation rate calculations?

Thank you.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_28&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=Tmjil_omrRexkruGYF3npc50yQDgblVGMV9ONPaZD5ObpLbFHtSdVQfwTayQ1G9E&s=Fzi7-E5k7MC5cS_ftrG3DvMdMu6U8FvAPLDMU6iKoyI&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3KSRNW6BPUPYGXA4RDUZ3OF5ANCNFSM5NVZ4BGQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=Tmjil_omrRexkruGYF3npc50yQDgblVGMV9ONPaZD5ObpLbFHtSdVQfwTayQ1G9E&s=p7fEyx14OPCVR8O3I3IjaCI-q1Nlb4k0B5Abddm1zM8&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=Tmjil_omrRexkruGYF3npc50yQDgblVGMV9ONPaZD5ObpLbFHtSdVQfwTayQ1G9E&s=0prsjPnynZVx-3tmqyjlWDJA0WUtesCia2hOwZqn3lo&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=Tmjil_omrRexkruGYF3npc50yQDgblVGMV9ONPaZD5ObpLbFHtSdVQfwTayQ1G9E&s=2wgn_fLEmF4r3cqUuJZ2m_zSB6dao48rU5RtwnA0JDI&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
