### ISSUE TITLE
CRAM files

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#30]
Hello,
Can all the various steps of the pipeline utilize CRAM instead of BAM files?

Also, note that the first extract_tags.py steps seems to only accept fastq, but not fastq.gz.

Thanks.

**Comment by fa8sanger** [comment]
Hi,

All the programs should accept CRAM files as they rely on the htslib library, but let us know if any doesn't.

About extract_tags.py, it’s inconvenient not to accept fastq.gz. It should be relatively easy to modify extract_tags.py to work with fastq.gz if you want to give it a try. Anyways, I’ll add this to our TODO list.



On 27 Feb 2022, at 23:56, gevro ***@***.******@***.***>> wrote:



Hello,
Can all the various steps of the pipeline utilize CRAM instead of BAM files?

Also, note that the first extract_tags.py steps seems to only accept fastq, but not fastq.gz.

Thanks.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_30&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=w0btqLoHKxpg0mFFtCdI7Y_YG-cd34SaJwv43TgCBz1DcWDtZTKgxqgiwdRXGZwy&s=QjIhmBWAaYglIqQFh-5rihVOGZuMFGKvvrNx9Riv8RQ&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3IIXHV7QY3VWDTIXITU5K22DANCNFSM5PPUAX7Q&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=w0btqLoHKxpg0mFFtCdI7Y_YG-cd34SaJwv43TgCBz1DcWDtZTKgxqgiwdRXGZwy&s=4DX9l4fynOHioUPVhgtE3VCm_3snY_ouiaRey0nWSBM&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=w0btqLoHKxpg0mFFtCdI7Y_YG-cd34SaJwv43TgCBz1DcWDtZTKgxqgiwdRXGZwy&s=sifcB9HS7kS3L5qp_9yhJ1zTmEC7gaTUegoRXFTf7AU&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=w0btqLoHKxpg0mFFtCdI7Y_YG-cd34SaJwv43TgCBz1DcWDtZTKgxqgiwdRXGZwy&s=eDvzgGe5O4BRtsy9eY0Vpds4cyNmrLYQMW51Mtz2iEA&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Ok thanks.
