### ISSUE TITLE
Within-plate cross-contamination

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#31]
Hi,
Is there any part of the existing pipeline that can automatically filter out within-plate cross-contamination? We don't necessarily know if this happened, but just in case, we'd like to apply this filter. We can build our own filtering for this, but wondering if the existing pipeline already has something to do this.

Thanks.

**Comment by fa8sanger** [comment]
Hi, That’s not part of the pipeline. When I’ve needed to do that I’ve used bam2R (R deepsnv package), getting the base counts for each mutation in each bam file (deduplicated bams). Let me know if you need help with that (direct message preferably).



On 8 Mar 2022, at 01:00, gevro ***@***.******@***.***>> wrote:



Hi,
Is there any part of the existing pipeline that can automatically filter out within-plate cross-contamination? We don't necessarily know if this happened, but just in case, we'd like to apply this filter. We can build our own filtering for this, but wondering if the existing pipeline already has something to do this.

Thanks.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_31&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=KGnyylHOjV5Q9_wjTgnSrVXHar6xGjIvo2fVZqt-omHT-j_PG_2BcyjxPbzstPjX&s=3y2RZhUIiztFM15D0uIU4TSo_0GvGv9pWdCMTccTT5U&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3MEXA3XYF6TERPPGW3U62RBHANCNFSM5QE4YQNQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=KGnyylHOjV5Q9_wjTgnSrVXHar6xGjIvo2fVZqt-omHT-j_PG_2BcyjxPbzstPjX&s=acW4l2vCNDbFGf4jrE3YofQk0YbqkjgDTztlgMBB5m8&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=KGnyylHOjV5Q9_wjTgnSrVXHar6xGjIvo2fVZqt-omHT-j_PG_2BcyjxPbzstPjX&s=nyMLMipyg4Wbl6dEIGzP4DhaWt2ubCjUlNLIaBPo9K8&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=KGnyylHOjV5Q9_wjTgnSrVXHar6xGjIvo2fVZqt-omHT-j_PG_2BcyjxPbzstPjX&s=lShKkWJno_NkFSDhsEAsHSnBbRYtsecvqqPXM94cUCQ&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
