### ISSUE TITLE
Output files question

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#33]
Hi,
What is the difference between these two files? (and associated files)
results.subst_asym.pdf  
results.mismatches.subst_asym.pdf  

The documentation isn't too clear about the difference, and they seem to show similar categories, but different mutation counts.

Thanks.

**Comment by fa8sanger** [comment]
According to the README, the “mismatches” files show the asymmetries and pyrimidine/purine-based trinucleotide substitution profiles for single-strand consensus calls. These profiles are useful to understand DNA damage during library preparation.

Single-strand consensus calls are calls supported by all the reads coming from one of the two original strands but not supported by the reads coming from the other strand in the read bundle. Does that make sense?

The “subst_asym.pdf” shows the asymmetries in the duplex calls (supported by all reads in the read bundle). Complementary substitutions (e.g. G>T vs C>A) are polarised based on the distance to the closest breakpoint, and 5’ end. Ext Data Fig 1d may be helpful to understand this.


On 20 Mar 2022, at 22:54, gevro ***@***.******@***.***>> wrote:



Hi,
What is the difference between these two files? (and associated files)
results.subst_asym.pdf
results.mismatches.subst_asym.pdf

The documentation isn't too clear about the difference, and they seem to show similar categories, but different mutation counts.

Thanks.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_33&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=NZ3UTq7-S-A9IbT2vMQLwBETguHXXUJuWQ9izA2yXwLWukOUVZi4tGK9YGi7l72n&s=2Y35dZSxZzWzS8tnYY3ntTIRG4a6hnOeX4LRocCaxiM&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3ITBUWCGPOIXMAGIVLVA6UEBANCNFSM5RGESPJQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=NZ3UTq7-S-A9IbT2vMQLwBETguHXXUJuWQ9izA2yXwLWukOUVZi4tGK9YGi7l72n&s=decwdI0GvUtcKj74YuuoKAdNnkl5ZUg7Ekir_XfRg6o&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=NZ3UTq7-S-A9IbT2vMQLwBETguHXXUJuWQ9izA2yXwLWukOUVZi4tGK9YGi7l72n&s=OpSKu9lbt_bIfQquGv4M2DYdHShOEMg4nr5BDrOj6Eo&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=NZ3UTq7-S-A9IbT2vMQLwBETguHXXUJuWQ9izA2yXwLWukOUVZi4tGK9YGi7l72n&s=-FW3SANkk8RO-IcEIdVohkcJF3TdTO-aCmwBbSxXAEo&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Ok thanks.
