### ISSUE TITLE
Mutation count per cell

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#34]
Hi,
Does the Nanoseq pipeline output # mutations per cell, similar to what is in the paper? I don't see that in the output, only mutation burden per basepair.

If not, do you simply use the size of the reference genome * mutation burden to get this number per haploid cell? Or is there a more sophisticated way you do this, with correction for trinucleotide context, etc?

Thanks.

**Comment by fa8sanger** [comment]
Hi, Just multiply the corrected burden (which is corrected for trinuc composition) by the size of the genome (haploid or diploid) to get muts/cell


On 5 Apr 2022, at 03:59, gevro ***@***.******@***.***>> wrote:



Hi,
Does the Nanoseq pipeline output # mutations per cell, similar to what is in the paper? I don't see that in the output, only mutation burden per basepair.

If not, do you simply use the size of the reference genome * mutation burden to get this number per haploid cell? Or is there a more sophisticated way you do this, with correction for trinucleotide context, etc?

Thanks.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_34&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=Sqsb7NH6GrwQmwdKZMqkbIQbzJZm5Kr-fe35e214jYj_JhG2Ms1e1lD8SagNp65P&s=UATXyHJk0AZS8xQZBDSPAcUosV5dnZxlu42iWFCkTnw&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3JMFY6H6T4AFFRIWITVDOUCXANCNFSM5SRK73RA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=Sqsb7NH6GrwQmwdKZMqkbIQbzJZm5Kr-fe35e214jYj_JhG2Ms1e1lD8SagNp65P&s=hB_f7JpE7rMb3QCsknKtoyh3T_B56AfEpL58PN7qAp8&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thanks
