### ISSUE TITLE
bamaddreadbundles fails

### ISSUE THREAD

**Issue by mgp2022** [cancerit/NanoSeq#35]
Every time I run this function as written it fails:

bamaddreadbundles -I mapped_od.bam -O filtered.bam

Is there an alternative way to input this?

**Comment by fa8sanger** [comment]
That’s how bamaddreadbundles is supposed to be run. Can you provide more details on the error messages? Also, if you share a minibam of your input bam I could test it.


On 5 Apr 2022, at 21:24, mgp2022 ***@***.******@***.***>> wrote:



Every time I run this function as written it fails:

bamaddreadbundles -I mapped_od.bam -O filtered.bam

Is there an alternative way to input this?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_35&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=nTO6j9Jzqo4CAsvfWgV4y8GXagF-Wch_aenuwKuq7W12nz2dXZho6jywuBLhb_ZU&s=JeyOHeEZZfIpR1Zy8Ke1Fi25ZPnkMZVOmikvj1OKsuY&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3NTBRWQAK4GRWY6LY3VDSOP3ANCNFSM5ST4PANA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=nTO6j9Jzqo4CAsvfWgV4y8GXagF-Wch_aenuwKuq7W12nz2dXZho6jywuBLhb_ZU&s=AdbOGGjVWGIJsy5jgnMeYHJxYrqQryhUcHwueQAcMYA&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by mgp2022** [comment]
I am using biobambam/2.0.180 on the server. 
It only gives me exit code 127, which means the command is not executable or not found. 

Could it be an issue with my input bam file? The bam file it generated was 7-9 times smaller than the inputted sam file. 

I run that like that:
cat mapped.sam | bamsormadup inputformat=sam rcsupport=1 threads=1 mapped.sam > mapped_od.bam

**Comment by fa8sanger** [comment]
bam files are much smaller than sam files.

That error means the shell is not finding bamaddreadbundles, make sure it is in your path or specify its absolute path

On 5 Apr 2022, at 22:11, mgp2022 ***@***.******@***.***>> wrote:



I am using biobambam/2.0.180 on the server.
It only gives me exit code 127, which means the command is not executable or not found.

Could it be an issue with my input bam file? The bam file it generated was 7-9 times smaller than the inputted sam file.

I run that like that:
cat mapped.sam | bamsormadup inputformat=sam rcsupport=1 threads=1 mapped.sam > mapped_od.bam

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_35-23issuecomment-2D1089355598&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=fT8695MTv9Cfc4cZjiRvSm8Pt0JRATqB3DhVax2e954-F7QY5qbI1ICs3cByX69N&s=8BKVyBEodkVRVYXomT8Ff1C7-p4aBUAsJ3ayT7sf7sE&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3IW5GFEOPSZYKR6F7LVDSUAHANCNFSM5ST4PANA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=fT8695MTv9Cfc4cZjiRvSm8Pt0JRATqB3DhVax2e954-F7QY5qbI1ICs3cByX69N&s=8vTVkiU5fd_nY9pJNflRRfzSOBS4Z90aHZUnnugDNq4&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by mgp2022** [comment]
I looked up the function list and I do not see bamaddreadbundles in the list of functions: 

Could this package (biobambam/2.0.180) rename it to any of the listed ones?

bam12auxmerge        bamfilteraux            bamrank
bam12split           bamfiltereofblocks      bamranksort
bam12strip           bamfilterflags          bamrecalculatecigar
bamadapterclip       bamfilterheader         bamrecompress
bamadapterfind       bamfilterheader2        bamrefextract
bamalignfrac         bamfilterk              bamrefinterval
bamauxmerge          bamfilterlength         bamreheader
bamauxmerge2         bamfiltermc             bamreplacechecksums
bamauxsort           bamfilternames          bamreset
bamcat               bamfilterrefid          bamscrapcount
bamchecksort         bamfilterrg             bamseqchksum
bamclipreinsert      bamfixmateinformation   bamsormadup
bamclipXT            bamfixpairinfo          bamsort
bamcollate2          bamflagsplit            bamsplit
bamdepth             bamindex                bamsplitdiv
bamdepthintersect    bamintervalcomment      bamstreamingmarkduplicates
bamdifference        bamintervalcommenthist  bamtofastq
bamdownsamplerandom  bammapdist              bamvalidate
bamexplode           bammarkduplicates       bamzztoname
bamexploderef        bammarkduplicates2      fastaexplod
bamfastcat           bammarkduplicatesopt    fastqtobam
bamfastexploderef    bammaskflags            fastqtobam2
bamfastnumextract    bammdnm                 normalisefasta
bamfastsplit         bammerge                populaterefcache
bamfeaturecount      bamnumericalindex
bamfillquery         bamnumericalindexstats

**Comment by fa8sanger** [comment]
Bamaddreadbundlea is part of Nanoseq not of biobambam
________________________________
