### ISSUE TITLE
Calculation of frequency for mismatches.subst_asym

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#36]
Hi,
If I want to calculate a single number that is the ssDNA damage/mutation rate, using the mismatches.subst_asym data, how would I do that?

I was thinking:
Numerator = sum of mutation counts from mismatches.subst_asym.tsv file => Is this correct?
Denominator = This is not clear what it should be. What are the total bases interrogated for the ssDNA mismatches? Is it 2 * [total bases from mut_burden.tsv file]? i.e. 2 * total duplex bases interrogated, since it is two single strand nucleotides per duplex base

Thanks.

**Comment by gevro** [comment]
Hi, Just checking if you have information on the above. Thank you.

**Comment by fa8sanger** [comment]
I think multiplying by 2 as you suggest would be better. Also, although it would make a very minor difference, you should sum the numerator to the "total duplex bases interrogated” in “mut_burden.tsv” because the total counts exclude mismatches sites (where there wasn’t an agreement between the two strands).

On 17 Apr 2022, at 23:41, gevro ***@***.******@***.***>> wrote:



Hi, Just checking if you have information on the above. Thank you.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_36-23issuecomment-2D1100961149&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=TjYp-fHq8x8oLpH90NmcMle07-fiFSvyUeb2XWgDQuTlWXArhO4JgyomKI1-aiUa&s=m9vvU-YKguQzdUsZfdC_HIvRx2Iuu9mmZQnCBU3i7Ik&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3OVF3TB7FNRV4DRWZDVFSHQHANCNFSM5S524BRQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=TjYp-fHq8x8oLpH90NmcMle07-fiFSvyUeb2XWgDQuTlWXArhO4JgyomKI1-aiUa&s=1sO2FY62kKK6HKyQIpDVsRB-0Xi-bXhWCcEH-13mXfk&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thank you, makes sense.

**Comment by gevro** [comment]
Hi,
I wanted to clarify the above:
1. Does mismatches.subst_asym.tsv include only counts of mismatched SSC sites, or does it also include SSC sites that are duplex mutations?
2. Assuming the answer to (1) is that it includes only counts of mismatched SSC sites, in the above response, you said: "you should sum the numerator to the "total duplex bases interrogated” in “mut_burden.tsv” because the total counts exclude mismatches sites (where there wasn’t an agreement between the two strands)"
 => Did you mean to say:
"you should sum the DENOMINATOR to the "total duplex bases interrogated” in “mut_burden.tsv” because the total counts OF MISMATCHES.SUBST_ASYM.TSV INCLUDES ONLY mismatches sites (where there wasn’t an agreement between the two strands)"

Thank you!

**Comment by gevro** [comment]
Note: I just edited the above open question for clarity.

**Comment by gevro** [comment]
Hi, Just following up if you have a response to the above updated questions. Thank you!

**Comment by fa8sanger** [comment]
I meant num_SSC_mismatches / (num_SSC_mismatches + total_duplex_calls). You suggested to multiply by two, which would be reasonable in some scenarios. But not in cases where you want to, for example, calculate the rate of G oxidation because in the other strand there would be a C

**Comment by gevro** [comment]
Thanks! Just to follow-up:

1. Does mismatches.subst_asym.tsv include only counts of single-strand mismatches, or does it also include duplex mutations?

2. Which of these would be the right calculation for ssDNA burden (# of ssc mismatches per total interrogated ssDNA bases)?

Option A:
[sum of counts from mismatches.subst_asym.tsv] / ([sum of counts from mismatches.subst_asym.tsv] + 2 * [total base pairs interrogated from the mut_burden.tsv file])
 => This would be the case if [total base pairs interrogated from the mut_burden.tsv file] excludes mismatched bases but includes the bases on their opposite strands that match the reference

Option B:
[sum of counts from mismatches.subst_asym.tsv] / (2* ([sum of counts from mismatches.subst_asym.tsv] + [total base pairs interrogated from the mut_burden.tsv file]))
 => This would be the case if [total base pairs interrogated from the mut_burden.tsv file] excludes both mismatched bases and the bases on their opposite strands that match the reference

Option C:
[sum of counts from mismatches.subst_asym.tsv] / (2* [total base pairs interrogated from the mut_burden.tsv file])
 => This would be the case if [total base pairs interrogated from the mut_burden.tsv file] includes both the mismatched bases and the bases on their opposite strands that match the reference

**Comment by fa8sanger** [comment]
1. Only single-strand mismatches
2. As I said, it depends on what you want to report. C is not right, though. For overall SSC rate I would go for B, for base-specific rates I would do a modification of A (num_ssc_G / (num_ssc_G + num_G_bases_called)
