### ISSUE TITLE
Calculating post-filtering (final) efficiency

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#38]
Hi,
What is the most accurate way to calculate post-filtering (final) efficiency? (Since the nanoseq pipeline outputs pre-filtering efficiency.)

[Is it 'total variant + reference' from summary.txt] / [read length * NUM_SEQUENCED_READS from efficiency.tsv] ?

That seems to give a fairly low post-filtering efficiency.

For one sample we have EFFICIENCY = 0.042, and post-filtering efficiency of 0.013.

This is a ratio of post-filtering / pre-filtering efficiency = 0.31. But it should be ~ 0.04/0.07 = 0.57.
This means our filtering is removing twice as much as usual.

This library has:
F-EFF	0.2498932
DUPLICATE_RATE	0.879531654135803
physical coverage            208636359 (I'm assuming this reflects coverage of the undiluted nanoseq germline reference)

These are the var job parameters:
-a 50 -b 0 -c 0 -f 0.9 -i 1 -m 8 -n 3 -p 0 -q 60 -r 144 -v 0.01 -x 8 -z 15

Is there any way to figure out what is causing the higher than expected filtering?

Thanks!

**Comment by fa8sanger** [comment]
Hi,

I would use column “total” in mut_burden.tsv (the number of duplex bases passing filters) then divide by read length * NUM_SEQUENCED_READS

(This is an approximation because NUM_SEQUENCED_READS is NUM_SEQUENCED_READS_AFTER_FILTERING_IMPROPER_PAIRS.
You can find out how many reads were actually sequenced by counting the number of reads in the original file - before running bamaddreadbundles).

Your duplicate rates and strand drop outs look good. The duplicate rate is a bit on the higher end but good.

Something that can reduce the efficiency largely is using a matched normal with low coverage, as you are requiring a minimum coverage of 15 (-z).

Please, try again with column “total” and let me know.  Also, where did you get that the ratio should be 0.04/0.07 (just to be on the same page)?


On 16 May 2022, at 00:25, gevro ***@***.******@***.***>> wrote:



Hi,
What is the most accurate way to calculate post-filtering (final) efficiency? (Since the nanoseq pipeline outputs pre-filtering efficiency.)

[Is it 'total variant + reference' from summary.txt] / [read length * NUM_SEQUENCED_READS from efficiency.tsv] ?

That seems to give a fairly low post-filtering efficiency.

For one sample we have EFFICIENCY = 0.042, and post-filtering efficiency of 0.013.

This is a ratio of post-filtering / pre-filtering efficiency = 0.31. But it should be ~ 0.04/0.07 = 0.57.
This means our filtering is removing twice as much as usual.

This library has:
F-EFF 0.2498932
DUPLICATE_RATE 0.879531654135803

These are the var job parameters:
-a 50 -b 0 -c 0 -f 0.9 -i 1 -m 8 -n 3 -p 0 -q 60 -r 144 -v 0.01 -x 8 -z 15

Is there any way to figure out what is causing the higher than expected filtering?

Thanks!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_38&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=ulpVnkxRKpQH1XFTYKpozoWGvJRooHIxe8EJWSPQ7-PWl1lxjiiHRYtZNQXsAV6n&s=xAT5ri6N5jI24ro7FR_-xnCKOWRMRwF5s3sWF_Nw08Q&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3JFGZ6CLYQXG227HD3VKGBXTANCNFSM5V7ZKNJQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=ulpVnkxRKpQH1XFTYKpozoWGvJRooHIxe8EJWSPQ7-PWl1lxjiiHRYtZNQXsAV6n&s=aEtoMcOu7JS_XBpJ4Ivycj50dO5GgmHe0slYek99FHs&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thanks.
1) Column 'total' from 'mut_burden.tsv' is the same number as total variant + reference' from summary.txt.
So the efficiency calculation comes out the same.

2) I'm getting the 0.04 and 0.07 ideal post and pre efficiency numbers from here: https://github.com/cancerit/NanoSeq/issues/21
 - Based on this you had said the Nature paper plotted post-filtering efficiency, and the plots show a max of ~0.04.
 - And the documentation of the pipeline on github says 0.07 which you said is the pre-filtering efficiency.
 - So I calculated 0.04/0.07 as the filtering ratio. Which is twice as high as what I am getting, indicating more filtering in our samples for some reason

3) For this sample, the undiluted Nanoseq germline sequencing had 134238923 clusters = 134238923 * 2 * 151 = 40.5 Gb, which is ~15x genome, which should be enough.
 => Is there any metric or QC I can look at to assess the actual germline coverage that the Nanoseq pipeline is "seeing"?
 => Any other parameters or issues that might be causing the higher than expected filtering?

Thanks so much!

**Comment by fa8sanger** [comment]
Hi,

It’s difficult to know what’s reducing your efficiency. You could have a look at some of the tables (directory “dsa”) and find out yourself how many rows do not pass your filters (each row is a base with duplex coverage).

At some point we removed the header of those tables for technical reasons. If you load one of the tables in R you can add the header back with:

colnames(mat) = c("type","chrom","chromStart","chromEnd","context","commonSNP","shearwater","bulkASXS","bulkNM","bulkForwardA","bulkForwardC","bulkForwardG","bulkForwardT","bulkForwardIndel","bulkReverseA","bulkReverseC","bulkReverseG","bulkReverseT","bulkReverseIndel","dplxBreakpointBeg","dplxBreakpointEnd","dplxBarcode","dplxBundleType","dplxASXS","dplxCLIP","dplxNM","dplxf1r2A","dplxf1r2C","dplxf1r2G","dplxf1r2T","dplxf1r2Indel","dplxf2r1A","dplxf2r1C","dplxf2r1G","dplxf2r1T","dplxf2r1Indel","dplxCQf1r2A","dplxCQf1r2C","dplxCQf1r2G","dplxCQf1r2T","dplxCQf2r1A","dplxCQf2r1C","dplxCQf2r1G","dplxCQf2r1T","bulkProperPair","dplxProperPair")

Alternatively, you could play with the variant calling, reducing “-z”, increasing “-c”, increasing “-n”, etc

Let me know how it goes...

On 16 May 2022, at 13:51, gevro ***@***.******@***.***>> wrote:



Thanks.

  1.  Column 'total' from 'mut_burden.tsv' is the same number as total variant + reference' from summary.txt.
So the efficiency calculation comes out the same.

  2.  I'm getting the 0.04 and 0.07 ideal post and pre efficiency numbers from here: #21 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_21&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=2fdZ0uzyRKD6qpnyFq-HO4BdbMO7-ISlFQvzoE76-_hyWp0AKkCecH-eHVRQMv5R&s=gON8sDNT4XHwZIySNr4L0Von1FeSpVUrVFiG4PJDx7Y&e=>

  *   Based on this you had said the Nature paper plotted post-filtering efficiency, and the plots show a max of ~0.04.
  *   And the documentation of the pipeline on github says 0.07 which you said is the pre-filtering efficiency.
  *   So I calculated 0.04/0.07 as the filtering ratio. Which is twice as high as what I am getting, indicating more filtering in our samples for some reason

  1.  For this sample, the undiluted Nanoseq germline sequencing had 134238923 clusters = 134238923 * 2 * 151 = 40.5 Gb, which is ~15x genome, which should be enough.
=> Is there any metric or QC I can look at to assess the actual germline coverage that the Nanoseq pipeline is "seeing"?
=> Any other parameters or issues that might be causing the higher than expected filtering?

Thanks so much!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_38-23issuecomment-2D1127633807&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=2fdZ0uzyRKD6qpnyFq-HO4BdbMO7-ISlFQvzoE76-_hyWp0AKkCecH-eHVRQMv5R&s=Ec_WGLBxov45L1FseMl8SVwxJ-Kn-7hDc12QPP3bqHg&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3MUP6FMHMUPXXLGGLLVKJAENANCNFSM5V7ZKNJQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=2fdZ0uzyRKD6qpnyFq-HO4BdbMO7-ISlFQvzoE76-_hyWp0AKkCecH-eHVRQMv5R&s=Ee0CF17RXYjcFj0ork9EBVm-RdD0L7U9mRpYfe60Lg4&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
I actually just checked 3 other samples (from different individuals) each of which used standard WGS germline reference, instead of undiluted Nanoseq library, and it is much better:

Post-filter: 0.03945496
EFFICIENCY          0.064357265546671
Ratio = 0.61

Post-filter: 0.03656284
EFFICIENCY	0.0634863967382884
Ratio = 0.58

Post-filter: 0.02474188
EFFICIENCY	0.0495226153282478
Ratio = 0.5

This is run with the same parameters, except -b = 3, instead of -b = 0.

=> Does this mean that the issue is the undiluted Nanoseq germline data? From your experience, does using undiluted Nanoseq germline have lower post-filter efficiency that standard WGS? If so, then it might be just as cost-effective to sequence 90X standard WGS germline vs undiluted Nanoseq, because the former will have twice as high post-filtering efficiency.

=> Other than '-b' do you use any other different parameters for undiluted Nanoseq germline than standard WGS germline? Can you share what your var step parameters are for both, just to be sure we're not doing anything wrong?

Thanks!

**Comment by gevro** [comment]
Yeah that's probably the issue. To check undiluted Nanoseq complexity, do I just run efficiency_nanoseq.pl in the same way as I would for diluted Nanoseq?

**Comment by fa8sanger** [comment]
Yes, run it exactly the same as for any other library

On 16 May 2022, at 15:26, gevro ***@***.******@***.***>> wrote:



Yeah that's probably the issue. To check undiluted Nanoseq complexity, do I just run efficiency_nanoseq.pl in the same way as I would for diluted Nanoseq?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_38-23issuecomment-2D1127745343&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=X9uy_0Vs3uzMHw1V4ZExeghxu1nhH-slqnvY9qsyVARy8LV2idFxXJ4CldxFDZ2y&s=GYuENmfBT3d15ZCpPbvfgIWBZw8eZAwFws5yR5KVHWI&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3OPQRH4GEUBOWIJPNLVKJLI7ANCNFSM5V7ZKNJQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=X9uy_0Vs3uzMHw1V4ZExeghxu1nhH-slqnvY9qsyVARy8LV2idFxXJ4CldxFDZ2y&s=c--KLCuPtQosfHlrMpjk4sRoZArE5pavsDYt9_pqnHg&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Here are the results for the problematic undiluted Nanoseq germline. Based on efficiency, it looks fine to me.
So I'm still confused what the problem might be? If the read depth was fine, and the duplication rate low for the undiluted Nanoseq library, then why would our post-filtering efficiency be half of what it should be, relative to samples with standard germline WGS?
```
NUM_UNIQUE_READS	186907296
NUM_SEQUENCED_READS	208978294
DUPLICATE_RATE	0.105613829922451
# RB metrics are reported for chr/contig 1 only:
TOTAL_RBS	7159425
TOTAL_READS_IN_RBS	15750612
OK_RBS(2+2)	697
READS_PER_RB	1.099991
F-EFF	0.528558
EFFICIENCY	7.37537478966955e-05
GC_BOTH	0.4156189
GC_SINGLE	0.4114385
```

**Comment by fa8sanger** [comment]
Hi, that looks fine. You have ~ 9x for the matched normal which would translate into 27x on the NanoSeq regions, more than enough.
Then we are back to what I suggested: look for the impact of different filters (-n, -c...). You can do this by running the “var” command again or by inspecting yourself some of the tables (in “dsa”). It would also be useful to run samtools stats and samtools flagstats on your bams.


On 17 May 2022, at 00:46, gevro ***@***.******@***.***>> wrote:



Here are the results for the problematic undiluted Nanoseq germline. Based on efficiency, it looks fine to me.
So I'm still confused what the problem might be? If the read depth was fine, and the duplication rate low for the undiluted Nanoseq library, then why would our post-filtering efficiency be half of what it should be, relative to samples with standard germline WGS?

NUM_UNIQUE_READS        186907296
NUM_SEQUENCED_READS     208978294
DUPLICATE_RATE  0.105613829922451
# RB metrics are reported for chr/contig 1 only:
TOTAL_RBS       7159425
TOTAL_READS_IN_RBS      15750612
OK_RBS(2+2)     697
READS_PER_RB    1.099991
F-EFF   0.528558
EFFICIENCY      7.37537478966955e-05
GC_BOTH 0.4156189
GC_SINGLE       0.4114385


—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_38-23issuecomment-2D1128245355&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=QJBN58xFh4A6ariJrNaRq2-6TS3vulrinkcdXMY2NHPH9AtN46S6dydjDJv9sssk&s=rzHcTB6wrufVGocsaRNiHPgR6l88TggcQofy4Ts0QAM&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3O3MVQ5P6FWY2ZLKULVKLM3TANCNFSM5V7ZKNJQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=QJBN58xFh4A6ariJrNaRq2-6TS3vulrinkcdXMY2NHPH9AtN46S6dydjDJv9sssk&s=fmN_T7tkElU6ZFpeaogaTqrmgbH5euP4cBpZC3GYtkc&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
