### ISSUE TITLE
extract_tags.py error

### ISSUE THREAD

**Issue by MariaZhi** [cancerit/NanoSeq#41]
Hello,

I'm trying to run extract_tags.py on zipped and unzipped fastq files, however, I get the same error when checking the read length.

Here is the code I run:

_python3 /home/mzhivagui/nano_env/NanoSeq/python/extract_tags.py -a S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_1.fq -b S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_2.fq -c S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_R1.fastq -d S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_R2.fastq -m 3 -s 4 -l 151_

And here is the error I get:

**Traceback (most recent call last):
  File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 210, in <module>
    ExtractTags(args.a, args.b, args.c, args.d, args.m, args.s, args.l)
  File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 148, in __init__
    self.extract_tags()
  File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 185, in extract_tags
    r1.trim_sequence(self.skips)
  File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 114, in trim_sequence
    assert len(self.sequence) == self.readlength - skips
AssertionError**

What could be the cause?

Many thanks!
Best,
Maria

**Comment by fa8sanger** [comment]
Hi Maria,

Could you send a few reads in fastq to check?
I may not be able to do the tests though, going on holidays today. Raul, could you give it a go?

Best,
Federico




On 28 Jul 2022, at 23:41, MMZ ***@***.******@***.***>> wrote:



Hello,

I'm trying to run extract_tags.py on zipped and unzipped fastq files, however, I get the same error when checking the read length.

Here is the code I run:

python3 /home/mzhivagui/nano_env/NanoSeq/python/extract_tags.py -a S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_1.fq -b S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_2.fq -c S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_R1.fastq -d S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_R2.fastq -m 3 -s 4 -l 151

And here is the error I get:

Traceback (most recent call last):
File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 210, in
ExtractTags(args.a, args.b, args.c, args.d, args.m, args.s, args.l)
File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 148, in init
self.extract_tags()
File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 185, in extract_tags
r1.trim_sequence(self.skips)
File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 114, in trim_sequence
assert len(self.sequence) == self.readlength - skips
AssertionError

What could be the cause?

Many thanks!
Best,
Maria

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_41&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=GkpssYaFSGZnHo-GJGq8jBrSbtNUsqFkjhfKewlRYEsD1zwrE0GD0OHeCJUbA5Bc&s=GarWQJEJ1bzSKEEFezOctTF-mpxS1LO8SDHJf4tt3Kg&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3JH4ZKJWYE4D77357DVWMEAPANCNFSM5463LOMA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=GkpssYaFSGZnHo-GJGq8jBrSbtNUsqFkjhfKewlRYEsD1zwrE0GD0OHeCJUbA5Bc&s=0XnioBVu8qSVduUO-BiwcygZw17pbOwoUJNdchofW3M&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by MariaZhi** [comment]
Hi Federico, Raul,

Here is the head of one of the fastq files:

**@A00564:531:HY7L5DSX3:2:1101:1063:1016 1:N:0:CTTAGGAC+NCTCCTAC
NATCTCAGCATCCACATATTCCCCATGAATAGACATAGAGGCGCACTACTCATGAGTGGCTGCTACAGTCATCCCATAGAAGAATGGGCCCTAATGTATTGAAATAAGCCACAATTATTGGAGGTTTATGTTATTTCTTACTTATTTATA
+
#FFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFF,FFFFFFF::FF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,F,F,F:FFFFF:FFFFFFFFFFFFFFF
@A00564:531:HY7L5DSX3:2:1101:1190:1016 1:N:0:CTTAGGAC+NCTCCTAC
NTTGTCATTGAATTTGTAGATTGCTTTTGGCAGTATGGTCATTTTCACAATATTGATTCTACCCATCCATGAGCATGGGATGTGTTTCCATTTGTTTGTATCATCTATGATTTCTTTCAGCAGTTTTTAGAGTTTCCTTGTATAGTCTTT
+
#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFF:FFFFFFFFFF:F:FFF:F,FFF:F:FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFF:FFFFFFF:FFF::FFFFFFFF,:,FF:FFFFF
@A00564:531:HY7L5DSX3:2:1101:1298:1016 1:N:0:CTTAGGAC+NCTCCTAC
NGTGTCACTCTAGCCTGGGCGACACAGCAAGACTCAAACAAAAACAAAAACAAAACAAAACAACAACAACAACAACATTACGTGGCCTGGAGTGGGAGCAGGTGCCTTTGTAGTCTAGGTTAACTACAAATGCCCACAAAATATACTAGG**

I am not sure if this #FFF is correct.

Best,
Maria

**Comment by rulixxx** [comment]
Hi Maria,

The quality value of '#' is OK its equivalent to a quality of 2 (very poor quality). Looking at the read length from those sequences it appears to be 150 (not 151). So I suspect that to be the issue.

If you still have problems check the read length of the entire file with:

zcat 33526_2#10_R1.fastq.gz | awk ' NR % 4 == 2  {print length}'  | uniq

It should just return one value (150 in this case).

Raul
________________________________

**Comment by MariaZhi** [comment]
Hi Raul,

My sequence looks indeed 150bp of length:

zcat S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_1.fq.gz | awk 'NR % 4 ==2 {print length; exit}' | uniq
150


However, what could be the reason? Does this mean that the library is bad, missing one bp?
Best,
Maria



On Jul 29, 2022, at 12:18 PM, Raul Alcantara ***@***.******@***.***>> wrote:


Hi Maria,

The quality value of '#' is OK its equivalent to a quality of 2 (very poor quality). Looking at the read length from those sequences it appears to be 150 (not 151). So I suspect that to be the issue.

If you still have problems check the read length of the entire file with:

zcat 33526_2#10_R1.fastq.gz | awk ' NR % 4 == 2 {print length}' | uniq

It should just return one value (150 in this case).

Raul
________________________________

**Comment by rulixxx** [comment]
Hello,

Read length is dependent on the sequencing kit being used. The sequencing lab might also change this to a custom value. Typically, it ranges from 100 to 200 bp for Illumina reads.

Raul
________________________________

**Comment by rulixxx** [comment]
Hi Maria,

The error being output by the code is not too useful in this case. Basically, its complaining that after trimming the read it doesn't match the correct length computed from the numbers provided as arguments to the script ( -m, -s , -l).

I would suspect that the file might be malformed or trimmed. Could you check that all reads have the same readlength (151 bp)

Raul

________________________________
From: MMZ ***@***.***>
Sent: Thursday, July 28, 2022 11:41 PM
To: cancerit/NanoSeq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cancerit/NanoSeq] extract_tags.py error (Issue #41)


Hello,

I'm trying to run extract_tags.py on zipped and unzipped fastq files, however, I get the same error when checking the read length.

Here is the code I run:

python3 /home/mzhivagui/nano_env/NanoSeq/python/extract_tags.py -a S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_1.fq -b S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_2.fq -c S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_R1.fastq -d S5_1_D_CKDL220014398-1A_HY7L5DSX3_L2_R2.fastq -m 3 -s 4 -l 151

And here is the error I get:

Traceback (most recent call last):
File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 210, in
ExtractTags(args.a, args.b, args.c, args.d, args.m, args.s, args.l)
File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 148, in init
self.extract_tags()
File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 185, in extract_tags
r1.trim_sequence(self.skips)
File "/home/mzhivagui/nanoseq/NanoSeq-develop/python/extract_tags.py", line 114, in trim_sequence
assert len(self.sequence) == self.readlength - skips
AssertionError

What could be the cause?

Many thanks!
Best,
Maria
