### ISSUE TITLE
part Error

### ISSUE THREAD

**Issue by MariaZhi** [cancerit/NanoSeq#43]
Hello,

I am getting an Indexing error after running the part command line.

Here is my code:
`singularity run ~/nanoseq/nanoseq_2.3.3.sif runNanoSeq.py -t 1 -A SC_1_U.filtered.neat.bam -B S5_1_D.filtered.bam -R GRCh38.d1.vd1.fa part -n 60`

and the error I am getting:

> command arguments :
> {'out': '.', 'index': None, 'max_index': None, 'threads': 1, 'ref': '/oasis/tscc/scratch/mzhivagui/Glyphosate/nanoseq_analysis/GRCh38.d1.vd1/GRCh38.d1.vd1.fa', 'normal': '/oasis/tscc/scratch/mzhivagui/Glyphosate/nanoseq_analysis/SC_1_U.filtered.neat.bam', 'tumour': '/oasis/tscc/scratch/mzhivagui/Glyphosate/nanoseq_analysis/S5_1_D.filtered.bam', 'subcommand': 'part', 'jobs': 60, 'excludeBED': None, 'excludeCov': None}
> 
> Parsing coverage files
> 
> Traceback (most recent call last):
>   File "/opt/wtsi-cgp/bin/runNanoSeq.py", line 662, in <module>
>     cc = int(iline.split('\t')[3])
> IndexError: list index out of range

Here is the header of one of the nov bed files (making sure it contains 4 columns):

> chr1    8100    8200    0
> chr1    8200    8300    0
> chr1    8300    8400    0
> chr1    8400    8500    0
> chr1    8500    8600    0
> chr1    8600    8700    0
> chr1    8700    8800    0
> chr1    8800    8900    0
> chr1    8900    9000    0
> chr1    9000    9100    0
> chr1    9100    9200    0
> chr1    9200    9300    0
> chr1    9300    9400    0
> chr1    9400    9500    0
> chr1    9500    9600    0
> chr1    9600    9700    0
> chr1    9700    9800    0
> chr1    9800    9900    0
> chr1    9900    10000   0
> chr1    10000   10100   113
> chr1    10100   10200   20
> chr1    10200   10300   0
> chr1    10300   10400   0
> chr1    10400   10500   0
> chr1    10500   10600   0
> chr1    10600   10700   0
> chr1    10700   10800   0
> chr1    10800   10900   0
> chr1    10900   11000   0

**Comment by rulixxx** [comment]
Hello Maria,

That looks like a corrupt file that is missing the fourth column. Not sure exactly what happened, but I guess something went wrong with the cov step. It shouldn't have allowed you to progress if cov files were not generated correctly, but something got messed regardless. Anyways I'd clear all the files and give it another try.

BTW for the cov stage you might want to use --exclude "chrM,chr%_random,chrUn_%,chr%_alt,HLA-%" (or something similar) to ignore the non-standard contigs in GRCh38. In addition I'd recommend the option -Q 10 , so that all reads with a mapQ less than 10 (poor mapping) don't get considered in the analysis. These two options should make the analysis run with better performance.

Raul
________________________________
From: MMZ ***@***.***>
Sent: Thursday, August 4, 2022 7:16 AM
To: cancerit/NanoSeq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cancerit/NanoSeq] part Error (Issue #43)


Hello,

I am getting an Indexing error after running the part command line.

Here is my code:
singularity run ~/nanoseq/nanoseq_2.3.3.sif runNanoSeq.py -t 1 -A SC_1_U.filtered.neat.bam -B S5_1_D.filtered.bam -R GRCh38.d1.vd1.fa part -n 60

and the error I am getting:

command arguments :
{'out': '.', 'index': None, 'max_index': None, 'threads': 1, 'ref': '/oasis/tscc/scratch/mzhivagui/Glyphosate/nanoseq_analysis/GRCh38.d1.vd1/GRCh38.d1.vd1.fa', 'normal': '/oasis/tscc/scratch/mzhivagui/Glyphosate/nanoseq_analysis/SC_1_U.filtered.neat.bam', 'tumour': '/oasis/tscc/scratch/mzhivagui/Glyphosate/nanoseq_analysis/S5_1_D.filtered.bam', 'subcommand': 'part', 'jobs': 60, 'excludeBED': None, 'excludeCov': None}

Parsing coverage files

Traceback (most recent call last):
File "/opt/wtsi-cgp/bin/runNanoSeq.py", line 662, in
cc = int(iline.split('\t')[3])
IndexError: list index out of range

Here is the header of one of the nov bed files (making sure it contains 4 columns):

chr1 8100 8200 0
chr1 8200 8300 0
chr1 8300 8400 0
chr1 8400 8500 0
chr1 8500 8600 0
chr1 8600 8700 0
chr1 8700 8800 0
chr1 8800 8900 0
chr1 8900 9000 0
chr1 9000 9100 0
chr1 9100 9200 0
chr1 9200 9300 0
chr1 9300 9400 0
chr1 9400 9500 0
chr1 9500 9600 0
chr1 9600 9700 0
chr1 9700 9800 0
chr1 9800 9900 0
chr1 9900 10000 0
chr1 10000 10100 113
chr1 10100 10200 20
chr1 10200 10300 0
chr1 10300 10400 0
chr1 10400 10500 0
chr1 10500 10600 0
chr1 10600 10700 0
chr1 10700 10800 0
chr1 10800 10900 0
chr1 10900 11000 0

**Comment by rulixxx** [comment]
Hi Maria,

Just came back from vacation an I was wondering if you had managed to get the Nanoseq code working.

Raul
________________________________

**Comment by MariaZhi** [comment]
Hi,

Not through nextflow.

I’m still having issues with that.

Maria Zhivagui, PhD

On 17 Aug 2022, at 15:07, Raul Alcantara ***@***.***> wrote:

﻿

Hi Maria,

Just came back from vacation an I was wondering if you had managed to get the Nanoseq code working.

Raul
________________________________
