### ISSUE TITLE
Genomic masks for hg38

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#45]
Hi, Do you have available genomic masks for hg38?

**Comment by gevro** [comment]
What would the contig exclude string be for this, in the 'cov' step?

**Comment by fa8sanger** [comment]
I run it with these options:
  --exclude "MT,hs37d5,GL%,JH%,GJ%,KL%,AABR%,AAG%,NC_%,KI%,chrM,hs37d5"
  --larger 100000


On 21 Oct 2022, at 18:41, gevro ***@***.******@***.***>> wrote:



What would the contig exclude string be for this, in the 'cov' step?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_45-23issuecomment-2D1287259032&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=IM9mZ9g48WG7pnAuaEFnzaW_NOI1opWOnwU_8ucmoYqTqvsdgOFabSsqJ9kH7pEp&s=a-zeZOQexX5c5HPuytHxpuH_-bvscKqs-QmNZNld0qQ&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3PPX7SM7HVP5CGE3QDWELITNANCNFSM6AAAAAAQZ36SYU&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=IM9mZ9g48WG7pnAuaEFnzaW_NOI1opWOnwU_8ucmoYqTqvsdgOFabSsqJ9kH7pEp&s=D4bcfCRMrxMMjN72CR_-3CqN84WVNANr7FCpoH8eccY&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by fa8sanger** [comment]
that was for hg38, but this all depends on the chromosome names in the assembly you are using

On 24 Oct 2022, at 14:30, gevro ***@***.******@***.***>> wrote:



Isn't that for hg37? What contig filter do you use for hg38?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_45-23issuecomment-2D1289038667&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=K7SrXAKzpveV67dbVO-6Lr64cKwgfwnQx2aOw6p7RbW0xPVBp1udYBHsITS5xzb2&s=hXXggJ__P6u3_zu7AB2oVT0MdY6ZMGK11aWtaWohEFM&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3N424QW25BY4Z72LXTWE2FNZANCNFSM6AAAAAAQZ36SYU&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=K7SrXAKzpveV67dbVO-6Lr64cKwgfwnQx2aOw6p7RbW0xPVBp1udYBHsITS5xzb2&s=41StNysNaPBDu3qx1_yMs7LHkjw9fRdHbcAlIJrcLEw&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Also in the google drive link, what is the difference between files with GRCh38 and those without?

**Comment by fa8sanger** [comment]
The others are GRCh37

On 24 Oct 2022, at 14:37, gevro ***@***.******@***.***>> wrote:



Also in the google drive link, what is the difference between files with GRCh38 and those without?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_45-23issuecomment-2D1289049189&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=mxGw-OyPxOC40q6gPXUSjHg0Fqb39i9MKIa0mcASmH1308Uv8V84aqQZj4UMcsGL&s=bh-gNxFp674MZ2flZ_8B9DdcakJef2NqV-4NDStn8Sk&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3NDCFJLI6JZRQHVMSDWE2GJ5ANCNFSM6AAAAAAQZ36SYU&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=mxGw-OyPxOC40q6gPXUSjHg0Fqb39i9MKIa0mcASmH1308Uv8V84aqQZj4UMcsGL&s=RsT93Lv1Kx8vR8NiH7Y6fpxJ0oAaLPo7eE1lJ3bPqWw&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
