### ISSUE TITLE
Discordant results between hs37d5 and hg38

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#48]
Hi,
I'm having a strange issue. I ran the same sample (same input FASTQ files), and same germline reference with hs37d5 vs hg38.

For hs37d5, the number of lines in variants.csv = 715
For hg38, the number of lines in variants.csv = 716
 And they agree almost exactly for counts per chromosome.

However, for results.muts.tsv:
For hs37d5, the number of lines = 715
For hg38, the number of lines = 324

This is causing the mutation burden from hg38 analysis to be ~1/2 of the burden from hs37d5 analysis.

I confirmed in all these files that only the desired contigs are included, same for both genomes: 1-22 + X. The Nanoseq pipeline parameters were also the same for both hs37d5 and hg38.

What could explain this discrepancy?

**Comment by fa8sanger** [comment]
Hi, could you send me those four files to have a look? That’s very strange indeed.
Also, the command lines you used to run “dsa" and “var"
You can email me directly

On 26 Oct 2022, at 15:44, gevro ***@***.******@***.***>> wrote:



Hi,
I'm having a strange issue. I ran the same sample (same input FASTQ files), and same germline reference with hs37d5 vs hg38.

For hs37d5, the number of lines in variants.csv = 715
For hg38, the number of lines in variants.csv = 716
And they agree almost exactly for counts per chromosome.

However, for results.muts.tsv:
For hs37d5, the number of lines = 715
For hg38, the number of lines = 324

This is causing the mutation burden from hg38 analysis to be ~1/2 of the burden from hs37d5 analysis.

I confirmed in all these files that only the desired contigs are included, same for both genomes: 1-22 + X. The Nanoseq pipeline parameters were also the same for both hs37d5 and hg38.

What could explain this discrepancy?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_48&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=lggm6iTlkQclwB0M9b4WOTeileTmnIdx-kRGFPkibIUzzs_r99izi6A3utuxrEBM&s=7ou7yacbrnfMsQcnzt8F7NSqFTi7l7HWkLtnalPpiyU&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3KODYRXYTKPYJLPET3WFE7WJANCNFSM6AAAAAARPCNP4Q&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=lggm6iTlkQclwB0M9b4WOTeileTmnIdx-kRGFPkibIUzzs_r99izi6A3utuxrEBM&s=zkKdISDKy09tsXcAsTTVp0oipxcWKhRv2-Dh6BlRh9g&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
