### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#49]
Hi,
I have previously used v2.3.2. The current version is v3.2.1.

Do I need to change anything in the command line parameters between these versions? Or is everything the same?

**Comment by fa8sanger** [comment]
I would stick to v2.3.2. We have made some specific modifications, mainly for a new protocol we are working on. For general use both versions are equivalent.

On 21 Nov 2022, at 19:33, gevro ***@***.******@***.***>> wrote:



Hi,
I have previously used v2.3.2. The current version is v3.2.1.

Do I need to change anything in the command line parameters between these versions? Or is everything the same?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_49&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=7HnKxuylHQDF1-n_MkMgP9DptL90CvgiSRTnrVQKPShnPNOLaN0rvkxN8JJ4o0GH&s=atdzYyJZalV1kPbFE5tBwyOncjbYvfcilsIoXfnKW4g&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3OVAIMGBVO42LDAUMTWJPFBDANCNFSM6AAAAAASG7SV2Q&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=7HnKxuylHQDF1-n_MkMgP9DptL90CvgiSRTnrVQKPShnPNOLaN0rvkxN8JJ4o0GH&s=SKYLEyLLu3Jp6Ycdh-_fwdz-ST9u-gYdxAE-A0a4Jhk&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
