### ISSUE TITLE
Nextflow vs documentation differences

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#50]
Hi,
There are some differences in the parameters used in the Nextflow pipeline vs the main README. Can you please clarify for each parameter what you recommend?

params.var_c = 0.02 in Nextflow but 0 in main documentation
params.var_d = 2 in Nextflow but not specified in main documentation
params.indel_t3 = 136 in Nextflow but 135 in main documentation
params.indel_t5 = 8 in Nextflow but 10 in main documentation
params.indel_z = 15 in Nextflow but not specified in main documentation
params.indel_v = params.var_v in Nextflow but not specified in main documentation
params.indel_a = params.var_a in Nextflow but not specified in main documentation
params.indel_c = params.var_c in Nextflow but not specified in main documentation

Thanks!

**Comment by gevro** [comment]
EDIT: After reviewing default values, these are the remaining discrepancies:
params.var_c = 0.02 in Nextflow but 0 in main documentation
params.indel_t3 = 136 in Nextflow but 135 in main documentation
params.indel_t5 = 8 in Nextflow but 10 in main documentation
params.indel_c = params.var_c in Nextflow but not specified in main documentation

**Comment by fa8sanger** [comment]
I wouldn’t use the Nextflow version, it is not yet mature enough.

We need to update the documentation for some new parameters. In the meantime if you run "runNanoSeq.py var -h" you’ll get a description of all parameters

On 21 Nov 2022, at 20:26, gevro ***@***.******@***.***>> wrote:



EDIT: After reviewing default values, these are the remaining discrepancies:
params.var_c = 0.02 in Nextflow but 0 in main documentation
params.indel_t3 = 136 in Nextflow but 135 in main documentation
params.indel_t5 = 8 in Nextflow but 10 in main documentation
params.indel_c = params.var_c in Nextflow but not specified in main documentation

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_50-23issuecomment-2D1322602542&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=y5RL1KYFQFoRZ0HdctZjQ3QlzPQEEvZaKFZq3jP-H-9Oj2F6BUAEqBAgTmlq7XtR&s=SRiBCx1Q4DJLReHaHFb6SikjAZuASKdzuxG2Z_LoLfE&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3KSIHNP5NAQYFMNZJTWJPLHXANCNFSM6AAAAAASHAHSKM&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=y5RL1KYFQFoRZ0HdctZjQ3QlzPQEEvZaKFZq3jP-H-9Oj2F6BUAEqBAgTmlq7XtR&s=sfsJt09rZ5KF2iY1etOTJihu33XOuJijy1yl5PH295c&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
What specific parameter do you recommend for each of these?
var -c
indel -c
Indel t3
indel t5

Thanks

**Comment by gevro** [comment]
Hi, just checking if any answer on the last question?
Thank you!

**Comment by fa8sanger** [comment]
Hi,

last time I run the pipeline I used:

—c 0
  --t3 135 \\
  --t5 10 \\

—c 0.1 works very similarly


On 22 Nov 2022, at 12:10, gevro ***@***.******@***.***>> wrote:



What specific parameter do you recommend for each of these?
var -c
indel -c
Indel t3
indel t5

Thanks

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_50-23issuecomment-2D1323567274&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=q4fZiuuXVFtUY85NucHaxbAkBjOmuJj7ox72HW5s8Z8rIfO1ImQSp6zCVUYwPVlv&s=_rhL4eAdYtH_z3fNCrZZso3b7UMLAM5WSgrF0H1moRE&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3K5QBWGU46B3YB6ZWLWJSZ2PANCNFSM6AAAAAASHAHSKM&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=q4fZiuuXVFtUY85NucHaxbAkBjOmuJj7ox72HW5s8Z8rIfO1ImQSp6zCVUYwPVlv&s=_jUGz1dP_Loq5tPrdi60ShoUYhh8RKcecx2_hq7jYZI&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thanks. Just to confirm you use -c 0 for both var and indel?

**Comment by fa8sanger** [comment]
yes, I always try to use the same params for both

On 24 Nov 2022, at 16:34, gevro ***@***.******@***.***>> wrote:



Thanks. Just to confirm you use -c 0 for both var and indel?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_50-23issuecomment-2D1326663418&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=N9_6-fgWJoyAsKHRM07NmkaGjy-sxmIi1r7dvcKEJKqr05WkLi6MdRbE6zumZ7R3&s=RgBxycJNTqxj_KHZWkoPiVYEzqoHV9v5u5SGja8JAp0&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3KV3Q3KGXTRSIQV7ELWJ6KIDANCNFSM6AAAAAASHAHSKM&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=N9_6-fgWJoyAsKHRM07NmkaGjy-sxmIi1r7dvcKEJKqr05WkLi6MdRbE6zumZ7R3&s=TvV4RCvxFCdnDv7LIdy70gZhy3tloul5q587yY7VF64&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
