### ISSUE TITLE
bamaddreadbundles don't own a parameter to input cram reference file

### ISSUE THREAD

**Issue by Lidweixiang** [cancerit/NanoSeq#51]
Hi !
Recently I downloaded NanoSeq cram files and run the NanoSeq pipeline and I find bamaddreadbundles don't own a parameter to input reference file. So if I don't revise the header of cram files to provide my reference path, the error will occur like this:
[E::refs_load_fai] Failed to open reference file '/lustre/scratch120/npg_repository/references/Homo_sapiens/1000Genomes_hs37d5/all/fasta/hs37d5.fa'
Do you have any ideas about this issue? Thanks!

**Comment by fa8sanger** [comment]
Hi Weixiang,

I see… We will consider modifying bamaddreadbundles to allow for such cram compatibility but that may take time.

The easiest solution is that you convert the cram to bam with samtools - samtools will accept an input reference file. The resulting bam should work well.

samtools view -b -T <refgenome.fa> -o <file.bam> <file.cram>

Alternatively you could alter the header in the cram file with samtools reheader

Hope this helps



On 22 Nov 2022, at 14:41, Weixiang Wang ***@***.******@***.***>> wrote:



Hi !
Recently I downloaded NanoSeq cram files and run the NanoSeq pipeline and I find bamaddreadbundles don't own a parameter to input reference file. So if I don't revise the header of cram files to provide my reference path, the error will occur like this:
[E::refs_load_fai] Failed to open reference file '/lustre/scratch120/npg_repository/references/Homo_sapiens/1000Genomes_hs37d5/all/fasta/hs37d5.fa'
Do you have any ideas about this issue? Thanks!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_51&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=bT6KC5ehQqU2fV1At42Ohez1VL-MkcWGvMJ0ch-nmyADsLDy85UjaEBN4eYAQnJh&s=LmzfljsDPCndHfYumPqewqD47QDu9pgE-cK6Nn0KmIE&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3KOLJIGJT2YEJI2723WJTLQXANCNFSM6AAAAAASH4ZQWE&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=bT6KC5ehQqU2fV1At42Ohez1VL-MkcWGvMJ0ch-nmyADsLDy85UjaEBN4eYAQnJh&s=yxobwnbwfjUlCAzex_d01MgeDQO1Z6G8-ugqK2NcbQg&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by Lidweixiang** [comment]
That's quite helpful ! Thanks!
