### ISSUE TITLE
The NanoSeq libraries don't include a rb and mb tags in cram files

### ISSUE THREAD

**Issue by Lidweixiang** [cancerit/NanoSeq#52]
Hi!

Recently I downloaded some NanoSeq libraries from EGA and the file format is CRAM.
From the header of cram, I find that these batches files have been processed through bamsormadup.
But I don't find the rb and mb tags in cram files, so when I run the command 'bamaddreadbundles', the output is an empty file without any error information.
Do these data have another processing method? Thanks!

The cram file alignment item just as follows:

HX5_30654:3:1105:24139:35326	163	1	130920	0	5S51M4D95M	=131092	318	seuqence base_quality AS:i:131	XS:i:131	MQ:i:0	ms:i:6148	mc:i:131242	MC:Z:146M5S	MD:Z:51^AAAC33C61	NM:i:5	RG:Z:sample_name

And the cram file header like this:

BWA :
@PG	ID:bwa	PN:bwa	CL:/software/sciops/pkg/bwa-aligner/0.7.17/bin/bwa sampe /lustre/scratch117/core/sciops_repository/references/PhiX/Sanger-SNPs/all/bwa0_6/phix_unsnipped_short_no_N.fa /tmp/4ZEvjqKMvt/alnphix_bwa_aln_1_out /tmp/_ttODqcBbu/alnphix_bwa_aln_2_out /tmp/3AGj574Seg/alnphix_simple_cat1_out /tmp/fNwxShN36V/alnphix_simple_cat2_out	PP:bamadapterfind	VN:0.7.17-r1188

@PG	ID:bwa'	PN:bwa	CL:/software/sciops/pkg/bwa-aligner/0.7.17/bin/bwa mem -t 16 -p -Y -K 100000000 /lustre/scratch117/core/sciops_repository/references/Homo_sapiens/1000Genomes_hs37d5/all/bwa0_6/hs37d5.fa /tmp/vJmHcDe9tV/aln_alntgt_bamtofastq_out	PP:bamadapterclip	VN:0.7.17-r1188

bamsormadup:

@PG	ID:bamsormadup-7DFCB2C2	PN:bamsormadup	CL:/software/sciops/pkg/biobambam2/2.0.79/bin/bamsormadup threads=16 SO=coordinate level=0 verbose=0 fixmate=1 adddupmarksupport=1 tmpfile=/nfs/sf22/ILorHSany_sf22/analysis/190819_HX5_30654_A_H2Y7YCCX2/Data/Intensities/BAM_basecalls_20190822-144843/no_cal/archive/lane3/plex15/sample_name.tmp	PP:bambi.2-60D0E653	VN:2.0.79

**Comment by fa8sanger** [comment]
Hi,

sorry about that. Not sure what’s going on. Could you let me know which sample did you download and could you save the header and 1000 items to a bam file and upload to google drive or just email if that works?

The header should contain a call to bammarkduplicatesopt too:

@PG ID:bamsormadup PN:bamsormadup CL:/software/pkgg/biobambam2/2.0.79/bin/bamsormadup threads=12 SO=coordinate verbose=0 fixmate=1 rcsupport=1 tmpfile=/lustre/scratch120/esa-sv-20201215-01/IL_seq_data/analysis/221018_A00538_0751_AHMWNMDSX3/Data/Intensities/BAM_basecalls_20221020-035143/no_cal/archive/lane4/plex29/bsfopt_46050_4#29.tmp PP:bambi.2 VN:2.0.79

@PG ID:bammarkduplicatesopt PN:bammarkduplicatesopt CL:/software/pkgg/biobambam2/2.0.79/bin/bammarkduplicatesopt level=0 verbose=0 tmpfile=/lustre/scratch120/esa-sv-20201215-01/IL_seq_data/analysis/221018_A00538_0751_AHMWNMDSX3/Data/Intensities/BAM_basecalls_20221020-035143/no_cal/archive/lane4/plex29/bmdfopt_46050_4#29.tmp M=/lustre/scratch120/esa-sv-20201215-01/IL_seq_data/analysis/221018_A00538_0751_AHMWNMDSX3/Data/Intensities/BAM_basecalls_20221020-035143/no_cal/archive/lane4/plex29/46050_4#29.markdups_metrics.txt optminpixeldif=2500 PP:bamsormadup VN:2.0.79

Thank you!
Fede


On 23 Nov 2022, at 04:08, Weixiang Wang ***@***.******@***.***>> wrote:



Hi!

Recently I downloaded some NanoSeq libraries from EGA and the file format is CRAM.
From the header of cram, I find that these batches files have been processed through bamsormadup.
But I don't find the rb and mb tags in cram files, so when I run the command 'bamaddreadbundles', the output is an empty file without any error information.
Do these data have another processing method? Thanks!

The cram file alignment item just as follows:

HX5_30654:3:1105:24139:35326 163 1 130920 0 5S51M4D95M =131092 318 seuqence base_quality AS:i:131 XS:i:131 MQ:i:0 ms:i:6148 mc:i:131242 MC:Z:146M5S MD:Z:51^AAAC33C61 NM:i:5 RG:Z:sample_name

And the cram file header like this:

BWA :
@pg [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pg&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JMEby_PGr_tB_jd7NdFQi1c_mxPL0IW_iq__R1NOumOkD2QG7tOZFZHJFEHnv1Gg&s=qEDMCgT84WjyLLfCsx5xi8dHdQW8aCKMJV-vO-13P2s&e=> ID:bwa PN:bwa CL:/software/sciops/pkg/bwa-aligner/0.7.17/bin/bwa sampe /lustre/scratch117/core/sciops_repository/references/PhiX/Sanger-SNPs/all/bwa0_6/phix_unsnipped_short_no_N.fa /tmp/4ZEvjqKMvt/alnphix_bwa_aln_1_out /tmp/_ttODqcBbu/alnphix_bwa_aln_2_out /tmp/3AGj574Seg/alnphix_simple_cat1_out /tmp/fNwxShN36V/alnphix_simple_cat2_out PP:bamadapterfind VN:0.7.17-r1188

@pg [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pg&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JMEby_PGr_tB_jd7NdFQi1c_mxPL0IW_iq__R1NOumOkD2QG7tOZFZHJFEHnv1Gg&s=qEDMCgT84WjyLLfCsx5xi8dHdQW8aCKMJV-vO-13P2s&e=> ID:bwa' PN:bwa CL:/software/sciops/pkg/bwa-aligner/0.7.17/bin/bwa mem -t 16 -p -Y -K 100000000 /lustre/scratch117/core/sciops_repository/references/Homo_sapiens/1000Genomes_hs37d5/all/bwa0_6/hs37d5.fa /tmp/vJmHcDe9tV/aln_alntgt_bamtofastq_out PP:bamadapterclip VN:0.7.17-r1188

bamsormadup:

@pg [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pg&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JMEby_PGr_tB_jd7NdFQi1c_mxPL0IW_iq__R1NOumOkD2QG7tOZFZHJFEHnv1Gg&s=qEDMCgT84WjyLLfCsx5xi8dHdQW8aCKMJV-vO-13P2s&e=> ID:bamsormadup-7DFCB2C2 PN:bamsormadup CL:/software/sciops/pkg/biobambam2/2.0.79/bin/bamsormadup threads=16 SO=coordinate level=0 verbose=0 fixmate=1 adddupmarksupport=1 tmpfile=/nfs/sf22/ILorHSany_sf22/analysis/190819_HX5_30654_A_H2Y7YCCX2/Data/Intensities/BAM_basecalls_20190822-144843/no_cal/archive/lane3/plex15/sample_name.tmp PP:bambi.2-60D0E653 VN:2.0.79

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_52&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JMEby_PGr_tB_jd7NdFQi1c_mxPL0IW_iq__R1NOumOkD2QG7tOZFZHJFEHnv1Gg&s=6vQjHFfGLbdvwqZLYvioRogGKU7pBSLMiO-8bM1ag7U&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3MCR5XJDFTJ6SIFMHTWJWKDRANCNFSM6AAAAAASIQRU44&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JMEby_PGr_tB_jd7NdFQi1c_mxPL0IW_iq__R1NOumOkD2QG7tOZFZHJFEHnv1Gg&s=rC86UfWpqN40EQvsylbX7DpZbojr1hvupKSlrq0pKVY&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by Lidweixiang** [comment]
Dear Fede,


Thanks for your replying ! 


The NanoSeq library cram file I downloaded is 31663_5#15.cram from the paper 'Somatic mutation landscapes at single-molecule resolution' from EGA and the truncated cram file has been upload as attachment, thanks for your patience !


Best regards,
Weixiang


| |
王伟翔
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 11/23/2022 17:23 |
| To | ***@***.***> |
| Cc | Weixiang ***@***.***> ,
***@***.***> |
| Subject | Re: [cancerit/NanoSeq] The NanoSeq libraries don't include a rb and mb tags in cram files (Issue #52) |

Hi,

sorry about that. Not sure what’s going on. Could you let me know which sample did you download and could you save the header and 1000 items to a bam file and upload to google drive or just email if that works?

The header should contain a call to bammarkduplicatesopt too:

@PG ID:bamsormadup PN:bamsormadup CL:/software/pkgg/biobambam2/2.0.79/bin/bamsormadup threads=12 SO=coordinate verbose=0 fixmate=1 rcsupport=1 tmpfile=/lustre/scratch120/esa-sv-20201215-01/IL_seq_data/analysis/221018_A00538_0751_AHMWNMDSX3/Data/Intensities/BAM_basecalls_20221020-035143/no_cal/archive/lane4/plex29/bsfopt_46050_4#29.tmp PP:bambi.2 VN:2.0.79

@PG ID:bammarkduplicatesopt PN:bammarkduplicatesopt CL:/software/pkgg/biobambam2/2.0.79/bin/bammarkduplicatesopt level=0 verbose=0 tmpfile=/lustre/scratch120/esa-sv-20201215-01/IL_seq_data/analysis/221018_A00538_0751_AHMWNMDSX3/Data/Intensities/BAM_basecalls_20221020-035143/no_cal/archive/lane4/plex29/bmdfopt_46050_4#29.tmp M=/lustre/scratch120/esa-sv-20201215-01/IL_seq_data/analysis/221018_A00538_0751_AHMWNMDSX3/Data/Intensities/BAM_basecalls_20221020-035143/no_cal/archive/lane4/plex29/46050_4#29.markdups_metrics.txt optminpixeldif=2500 PP:bamsormadup VN:2.0.79

Thank you!
Fede


On 23 Nov 2022, at 04:08, Weixiang Wang ***@***.******@***.***>> wrote:



Hi!

Recently I downloaded some NanoSeq libraries from EGA and the file format is CRAM.
From the header of cram, I find that these batches files have been processed through bamsormadup.
But I don't find the rb and mb tags in cram files, so when I run the command 'bamaddreadbundles', the output is an empty file without any error information.
Do these data have another processing method? Thanks!

The cram file alignment item just as follows:

HX5_30654:3:1105:24139:35326 163 1 130920 0 5S51M4D95M =131092 318 seuqence base_quality AS:i:131 XS:i:131 MQ:i:0 ms:i:6148 mc:i:131242 MC:Z:146M5S MD:Z:51^AAAC33C61 NM:i:5 RG:Z:sample_name

And the cram file header like this:

BWA :
@pg [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pg&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JMEby_PGr_tB_jd7NdFQi1c_mxPL0IW_iq__R1NOumOkD2QG7tOZFZHJFEHnv1Gg&s=qEDMCgT84WjyLLfCsx5xi8dHdQW8aCKMJV-vO-13P2s&e=> ID:bwa PN:bwa CL:/software/sciops/pkg/bwa-aligner/0.7.17/bin/bwa sampe /lustre/scratch117/core/sciops_repository/references/PhiX/Sanger-SNPs/all/bwa0_6/phix_unsnipped_short_no_N.fa /tmp/4ZEvjqKMvt/alnphix_bwa_aln_1_out /tmp/_ttODqcBbu/alnphix_bwa_aln_2_out /tmp/3AGj574Seg/alnphix_simple_cat1_out /tmp/fNwxShN36V/alnphix_simple_cat2_out PP:bamadapterfind VN:0.7.17-r1188

@pg [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pg&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JMEby_PGr_tB_jd7NdFQi1c_mxPL0IW_iq__R1NOumOkD2QG7tOZFZHJFEHnv1Gg&s=qEDMCgT84WjyLLfCsx5xi8dHdQW8aCKMJV-vO-13P2s&e=> ID:bwa' PN:bwa CL:/software/sciops/pkg/bwa-aligner/0.7.17/bin/bwa mem -t 16 -p -Y -K 100000000 /lustre/scratch117/core/sciops_repository/references/Homo_sapiens/1000Genomes_hs37d5/all/bwa0_6/hs37d5.fa /tmp/vJmHcDe9tV/aln_alntgt_bamtofastq_out PP:bamadapterclip VN:0.7.17-r1188

bamsormadup:

@pg [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pg&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JMEby_PGr_tB_jd7NdFQi1c_mxPL0IW_iq__R1NOumOkD2QG7tOZFZHJFEHnv1Gg&s=qEDMCgT84WjyLLfCsx5xi8dHdQW8aCKMJV-vO-13P2s&e=> ID:bamsormadup-7DFCB2C2 PN:bamsormadup CL:/software/sciops/pkg/biobambam2/2.0.79/bin/bamsormadup threads=16 SO=coordinate level=0 verbose=0 fixmate=1 adddupmarksupport=1 tmpfile=/nfs/sf22/ILorHSany_sf22/analysis/190819_HX5_30654_A_H2Y7YCCX2/Data/Intensities/BAM_basecalls_20190822-144843/no_cal/archive/lane3/plex15/sample_name.tmp PP:bambi.2-60D0E653 VN:2.0.79

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_52&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JMEby_PGr_tB_jd7NdFQi1c_mxPL0IW_iq__R1NOumOkD2QG7tOZFZHJFEHnv1Gg&s=6vQjHFfGLbdvwqZLYvioRogGKU7pBSLMiO-8bM1ag7U&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3MCR5XJDFTJ6SIFMHTWJWKDRANCNFSM6AAAAAASIQRU44&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JMEby_PGr_tB_jd7NdFQi1c_mxPL0IW_iq__R1NOumOkD2QG7tOZFZHJFEHnv1Gg&s=rC86UfWpqN40EQvsylbX7DpZbojr1hvupKSlrq0pKVY&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




--
The Wellcome Sanger Institute is operated by Genome Research
Limited, a charity registered in England with number 1021457 and a
company registered in England with number 2742969, whose registered
office is 215 Euston Road, London, NW1 2BE.

**Comment by Lidweixiang** [comment]
Hi Fede,

Thanks for replying! 

The NanoSeq library cram file I downloaded is 31663_5#15.cram from the paper 'Somatic mutation landscapes at single-molecule resolution' from EGA and the truncated cram file has been uploaded as an attachment through e-mail, thanks for your patience!

Weixiang

**Comment by fa8sanger** [comment]
Hi Weixiang,

I didn’t get the attachment. I think to send attachments you need to message directly from your github account

Fede


On 23 Nov 2022, at 12:36, Weixiang Wang ***@***.******@***.***>> wrote:



Hi Fede,

Thanks for replying!

The NanoSeq library cram file I downloaded is 31663_5#15.cram from the paper 'Somatic mutation landscapes at single-molecule resolution' from EGA and the truncated cram file has been uploaded as an attachment through e-mail, thanks for your patience!

Weixiang

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_52-23issuecomment-2D1324995306&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=uTm2JK3A8dZ3EOHutnZbO96w1VBo0XedY7K1a4CdAbJl_FeG62FSrvF_UKSvfcJ6&s=xDsBfBYV-BHWRBOxF8zGTYkcwCMnLuOMFQ7BEs96gpI&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3KNEKN6DRM3SVY32QLWJYFV5ANCNFSM6AAAAAASIQRU44&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=uTm2JK3A8dZ3EOHutnZbO96w1VBo0XedY7K1a4CdAbJl_FeG62FSrvF_UKSvfcJ6&s=DSPovAoxAfDzytFHJdzEu-stGtMyd43gKLL6sRpDCiA&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by Lidweixiang** [comment]
[31663_5#15.bam.zip](https://github.com/cancerit/NanoSeq/files/10075844/31663_5.15.bam.zip)
I'm sorry for that, now I have uploaded the bam file again from Github.

**Comment by fa8sanger** [comment]
Hi Weixiang,

Those cram files were uploaded to EGA without the preprocessing. If you look at the cigar strings you’ll see that most alignments have a soft clipping of 4 or 5 bases. Those are the barcodes. Hence, the first step is to convert to fastq and run the python script to trim the reads and annotate the barcodes in the fastq header.

python extract-tags.py -a R1.fastq -b R2.fastq -c extrR1.fastq -d extrR2.fastq -m 3 -s 4 -l 151

Then bwa, bamsormadup, bammarkduplicatesopt, bamaddreadbundles…
I know it’s a pain to have to do all the pre-processing. Let me know if you find any problem in that endeavour.

Best,
Fede


On 23 Nov 2022, at 13:22, Weixiang Wang ***@***.******@***.***>> wrote:



31663_5#15.bam.zip [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_files_10075844_31663-5F5.15.bam.zip&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=WQw0-TVEuWMXs0umiv9whyOF6dyqWxZ2c9lohku4KtrgEIaMHB7VRPSPph2QRoCb&s=MYXbb8XbdH7cSBk8_8NN-PZeGIElILLQnVocLUOC32E&e=>
I'm sorry for that, now I have uploaded the bam file again from Github.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_52-23issuecomment-2D1325062726&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=WQw0-TVEuWMXs0umiv9whyOF6dyqWxZ2c9lohku4KtrgEIaMHB7VRPSPph2QRoCb&s=v8YZmemBj0fo_N_1FtG_FSxv5GFV7JYJUsY7Fwa-sHM&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3OKGOIKTW45I5I7AMTWJYLBBANCNFSM6AAAAAASIQRU44&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=WQw0-TVEuWMXs0umiv9whyOF6dyqWxZ2c9lohku4KtrgEIaMHB7VRPSPph2QRoCb&s=P7S18mIingG0KM_EOJtxvAGuVZBYJdLNvKEgiSvmWMw&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by Lidweixiang** [comment]
Hi Fede,

Thanks for your help! That's right, I will transform the cram files to fastq and rerun the NanoSeq pre-processing workflow according to the markdown file and I believe that the problem will be solved soon, thanks!

Best regards,
Weixiang

**Comment by fa8sanger** [comment]
Hi Weixiang, Just a quick note. Don’t assume all cram files need the entire pre-processing. It is possible that the latest ones have already been pre-processed

Best,
Fede


On 23 Nov 2022, at 14:42, Weixiang Wang ***@***.******@***.***>> wrote:



Hi Fede,

Thanks for your help! That's right, I will transform the cram files to fastq and rerun the NanoSeq pre-processing workflow according to the markdown file and I believe that the problem will be solved soon, thanks!

Best regards,
Weixiang

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_52-23issuecomment-2D1325177829&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=adPCIF6cmvf7vENvAbOoX7D9V_MMLA1xslAA-cv1VKXGeCxjBpyZw-5htidiUV74&s=6SjuJ1at_rFo2uEg_MPRSDCEcMCRQ3oDS8KbJXxoDcM&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3IF4ET3IYFLALQUZNLWJYUOVANCNFSM6AAAAAASIQRU44&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=adPCIF6cmvf7vENvAbOoX7D9V_MMLA1xslAA-cv1VKXGeCxjBpyZw-5htidiUV74&s=uhMqyBde0DHbYrj1NRTubCF1IWoM46mRr8BBjxml0DM&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
