### ISSUE TITLE
indel from v2.3.2 doesn't have -a -c -v -z arguments

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#53]
Hi,
I tried adding the -a -c -v -z parameters to indel, to change from the default, but I'm getting an 'unrecognized arguments' error.

I used to rely on the default values, but now I want to change from the default. It looks like 2.3.2 doesn't accept these parameters? See below for details.

Thanks!

Version: nanoseq_2.3.2

Command:
```
runNanoSeq.py --out $samplename -t 32 -A $germlinebam -B $nanoseqbam -R $reffasta indel -s $samplename -a 50 -c 0 -v 0.01 -z 15 --rb 2 --t3 135 --t5 10
```

Error:
```
usage: runNanoSeq.py [-h] [--out OUT] [-j INDEX] [-k MAX_INDEX] [-t THREADS]
                     -R REF -A NORMAL -B TUMOUR [-v]
                     {cov,part,dsa,var,indel,post} ...
runNanoSeq.py: error: unrecognized arguments: -a 50 -c 0 -v 0.01 -z 15
```

Help of indel:
```
usage: runNanoSeq.py indel [-h] [-s SAMPLE] [--rb RB] [--t3 T3] [--t5 T5] [--mc MC]

optional arguments:
  -h, --help            show this help message and exit
  -s SAMPLE, --sample SAMPLE
                        sample name in output vcf (sample_1)
  --rb RB               minimum reads in a bundle. (2)
  --t3 T3               excess bases above this value are trimmed from 3' (135)
  --t5 T5               bases to trim from 5' reads (10)
  --mc MC               minimum bulk coverage (16)
```

**Comment by fa8sanger** [comment]
Hi,

Not sure what’s wrong. Can you do

echo "runNanoSeq.py --out $samplename -t 32 -A $germlinebam -B $nanoseqbam -R $reffasta indel -s $samplename -a 50 -c 0 -v 0.01 -z 15 --rb 2 --t3 135 --t5 10"

and send the output?

Also check the dashes are conventional dashes




On 25 Nov 2022, at 13:57, gevro ***@***.******@***.***>> wrote:



Hi,
I tried adding the -a -c -v -z parameters to indel, to change from the default, but I'm getting an 'unrecognized arguments' error.

I used to rely on the default values, but now I want to change from the default. See below for details.

Thanks!

Version: nanoseq_2.3.2

Command:

runNanoSeq.py --out $samplename -t 32 -A $germlinebam -B $nanoseqbam -R $reffasta indel -s $samplename -a 50 -c 0 -v 0.01 -z 15 --rb 2 --t3 135 --t5 10


Error:

usage: runNanoSeq.py [-h] [--out OUT] [-j INDEX] [-k MAX_INDEX] [-t THREADS]
                     -R REF -A NORMAL -B TUMOUR [-v]
                     {cov,part,dsa,var,indel,post} ...
runNanoSeq.py: error: unrecognized arguments: -a 50 -c 0 -v 0.01 -z 15


Help of indel:

usage: runNanoSeq.py indel [-h] [-s SAMPLE] [--rb RB] [--t3 T3] [--t5 T5] [-a A] [-c C] [-z Z] [-v V]

options:
  -h, --help            show this help message and exit
  -s SAMPLE, --sample SAMPLE
                        sample name in output vcf (sample_1)
  --rb RB               minimum reads in a bundle. (2)
  --t3 T3               excess bases above this value are trimmed from 3' (136)
  --t5 T5               bases to trim from 5' reads (8)
  -a A                  minimum AS-XS (50)
  -c C                  fraction of clips (0.02)
  -z Z                  minimum normal coverage (mc) (15)
  -v V                  maximum normal VAF (0.01)


—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_53&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=4-NbiyHaLN7oQPN-yqs8WkAkIe5hTuPmg_BCe87VL2gUyAvGGP4qQGjjkqyqWovr&s=G1ApWdKT5Do8-TWwVLl2RQ1zoEwMIZgSeSy1hTiFEtk&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3P7WI7MTE3U657RX6TWKDAVLANCNFSM6AAAAAASLLCFCM&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=4-NbiyHaLN7oQPN-yqs8WkAkIe5hTuPmg_BCe87VL2gUyAvGGP4qQGjjkqyqWovr&s=iMl0rgCJfdDyjMdbzLvyyVE0nBsmDIOt5dIF5paYGNI&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Sorry, I updated my post above with the correct 2.3.2 --help output. I think the issue is that in v2.3.2 these a/c/v/z options don't exist yet?

Does that mean for 2.3.2, I can't exactly replicate the a/c/v/z parameters of var for the indel step?

I'm using 2.3.2, because of the recommendation to still use that rather than 3.2.1. If so, I can stick with 2.3.2 with only the 'mc' parameter.

**Comment by fa8sanger** [comment]
Feel free to update to v3.2.1, but the Nextflow pipeline control script is not mature, I would keep running the pipeline in a similar way to v2.3.2

On 25 Nov 2022, at 14:10, gevro ***@***.******@***.***>> wrote:



Sorry, I updated my post above with the correct 2.3.2 --help output. I think the issue is that in v2.3.2 these a/c/v/z options don't exist yet?

Does that mean for 2.3.2, I can't exactly replicate the a/c/v/z parameters of var for the indel step?

I'm using 2.3.2, because of the recommendation to still use that rather than 3.2.1. If so, I can stick with 2.3.2 with only the 'mc' parameter.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_53-23issuecomment-2D1327519266&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=DXPBXQ8sTsgpLYvGbzRMOX-3_wsA0IHqk8kBPRasCICOeZ3oltzjfPXRbXtpl81v&s=ovoCWEcsrDoRudEeu8mcY8zQCpi4NXvyTwgkv4JAT-o&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3NVQJQOECSFGS7H2P3WKDCDTANCNFSM6AAAAAASLLCFCM&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=DXPBXQ8sTsgpLYvGbzRMOX-3_wsA0IHqk8kBPRasCICOeZ3oltzjfPXRbXtpl81v&s=GR-5yi8swyOv0yPmo-lR7TgmeplFbRY_Wg4ZUCdSo6g&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thanks. Ok, I will update to 3.2.1, but will keep using my current step-by-step scripts instead of nextflow.
