### ISSUE TITLE
Cycle 6 issue when running full lane with only Nanoseq HpyCH4V libraries

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#54]
Hi,

For the first time instead of pooling with other types of libraries, we ran a full lane containing only Nanoseq HpyCH4V libraries, on Novaseq 6000.

We encountered a weird thing where in both read 1 and read 2, cycle # 6 comes out with low quality, and also it shows T and G bases, even though it should be 50% C and 50% A (probably miscalls due to the quality issue).

Have you all run lanes with only Nanoseq HpyCH4V before and seen this?
Maybe it's because of the Novaseq 2-color chemistry since C and A are both red such that all the clusters light up in that cycle?
T=Green, C=Red, A=Green/Red, G=No color

I'm assuming it's not relevant to data analysis since that base is skipped anyway.

See attached screenshots
<img width="832" alt="Screen Shot 2022-12-07 at 5 54 55 PM" src="https://user-images.githubusercontent.com/47928628/206315047-6186b8b7-6207-4350-aa40-008605e6bebc.png">
<img width="226" alt="Screen Shot 2022-12-07 at 5 55 01 PM" src="https://user-images.githubusercontent.com/47928628/206315049-eff3c7f4-234e-4c81-a0ee-17f747a0dd7f.png">
<img width="38" alt="Screen Shot 2022-12-07 at 5 55 03 PM" src="https://user-images.githubusercontent.com/47928628/206315050-5227cfd9-8688-41bb-8492-f667216a8818.png">

Thanks

**Comment by gevro** [comment]
Hello, just checking if you all have experienced this issue?

**Comment by fa8sanger** [comment]
No, I haven’t seen that drop in BQ before.
The bases seen (or not seen) at some positions look strange too.

***General read structure
  NNN degenerate 3-nucleotide tag
  X   spacer designed to avoid 'blooming' issues during sequencing
  T   overhang for ligation
  R   non-adaptor read

You can find NNNXTCAR, NNNTCAR at the beginning of reads. CA is half of the restriction site (TGCA). I would also expect 50% C/A at the 6th position.

Have you checked whether most reads have CA close to the beginning of the read?

I would trim the reads with extract_tags.py and see how they look. You can also check at IGV after mapping to verify there are TGCA at mapping coordinates




On 13 Dec 2022, at 16:42, gevro ***@***.******@***.***>> wrote:



Hello, just checking if you all have experienced this issue?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_54-23issuecomment-2D1349024990&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=8DsL_rnQluIf4vZtYDUL3i8YuGpXD3T4hTVlfUpTFnUHRsk9OSwE32x5rStrOhek&s=C9AHdsEANXz1p2eJsTuBZBE4O74BnsYS1WPzUyxNJX0&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3J3AAVUKRNKDYTF4V3WNCROFANCNFSM6AAAAAASXM76OI&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=8DsL_rnQluIf4vZtYDUL3i8YuGpXD3T4hTVlfUpTFnUHRsk9OSwE32x5rStrOhek&s=TPGVJlmzgbhXUfgM80M0CouHXYPrI2UNRuMnR0sKKWI&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Except for cycle 6, I believe the bases seen match expectation. We used HpyCH4V with the IDT CS adaptors with UUUXT/UUUT structure (X = skipped base)

The resulting expected structure is:
Cycles 1-3: UMI (25% random each base)
Cycle 4: 50% T, 25% G, 25% C
Cycle 5: 50% T, 50% C
Cycle 6: 50% C, 50% A
Cycle 7: 62.5% A, 12.5% T, 12.5% G, 12.5% C

Cycle 6 doesn't show the correct base composition, I think due the quality issue. 

How much % phiX do you all use when the lane/flow-cell is full of only Nanoseq libraries?
This was 1% phiX, and we will try higher next time (4%).

**Comment by fa8sanger** [comment]
I am not sure what % of phiX is used here but 4% sounds a lot to my inexperienced eye. I wouldn't worry, as long as the rest is ok. The 6th base won’t be in the final reads after trimming

On 13 Dec 2022, at 17:41, gevro ***@***.******@***.***>> wrote:



Except for cycle 6, I believe the bases seen match expectation. We used HpyCH4V with the IDT CS adaptors with UUUXT/UUUT structure (X = skipped base)

The resulting expected structure is:
Cycles 1-3: UMI (25% random each base)
Cycle 4: 50% T, 25% G, 25% C
Cycle 5: 50% T, 50% C
Cycle 6: 50% C, 50% A
Cycle 7: 62.5% A, 12.5% T, 12.5% G, 12.5% C

Cycle 6 doesn't show the correct base composition, I think due the quality issue.

How much % phiX do you all use when the lane/flow-cell is full of only Nanoseq libraries?
This was 1% phiX, and we will try higher next time (4%).

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_54-23issuecomment-2D1349239450&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=SXkPIK5tIEn68v9yktG5zpoIZ1hBMnTtZcxGFXmOKLPbJ_FNhfkOo6NRchpStTje&s=kfHe9IChXDxzftZVuwZdBbUKGGbq2dV2p8VKKd9a5eA&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3LSVWHCZ763UJGM42LWNCYNHANCNFSM6AAAAAASXM76OI&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=SXkPIK5tIEn68v9yktG5zpoIZ1hBMnTtZcxGFXmOKLPbJ_FNhfkOo6NRchpStTje&s=65BlkiLC6ENu6rN0CdsrqxPmj3626kQ-fbNd5g7wAEY&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
True. This shouldn’t affect data analysis since this base is skipped anyway.
