### ISSUE TITLE
Recommendation for mouse restriction enzyme

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#55]
Hi, Do you have a recommendation for a mouse restriction enzyme?

HpyCH4V generates an ok size range, but it creates peaks. I'm guessing because of repetitive elements?

Thanks!

<img width="782" alt="Screen Shot 2022-12-11 at 7 29 14 PM" src="https://user-images.githubusercontent.com/47928628/206938504-15347ad4-b3a8-41fe-8068-c3ec20c7900d.png">

<img width="786" alt="Screen Shot 2022-12-11 at 7 29 30 PM" src="https://user-images.githubusercontent.com/47928628/206938511-d92c7226-bf6a-4dde-bea1-09c6f17d341f.png">

**Comment by fa8sanger** [comment]
We noticed that too, but despite that HpyCH4V has been working well for mouse. You can try any blunt end restriction enzyme, and you can do in silico digestions to predict the fragment size distribution. Let us know if you find a better alternative

On 12 Dec 2022, at 00:30, gevro ***@***.******@***.***>> wrote:



Hi, Do you have a recommendation for a mouse restriction enzyme?

HpyCH4V generates an ok size range, but it creates peaks. I'm guessing because of repetitive elements?

Thanks!

[Screen Shot 2022-12-11 at 7 29 14 PM] [user-images.githubusercontent.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_47928628_206938504-2D15347ad4-2Db3a8-2D41fe-2D8068-2Dc3ec20c7900d.png&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JdiIZxBR5SXV83fLf52pghtwuzPd7taNtFVn9rwh-HaQ_D96riYyv53BjKvV4fKS&s=L-dOe62rwAegCd3FXOnOoJkjw-Vk8QUIGo1KH2Efayw&e=>

[Screen Shot 2022-12-11 at 7 29 30 PM] [user-images.githubusercontent.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_47928628_206938511-2Dd92c7226-2Dbf6a-2D4dde-2Dbea1-2D09c6f17d341f.png&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JdiIZxBR5SXV83fLf52pghtwuzPd7taNtFVn9rwh-HaQ_D96riYyv53BjKvV4fKS&s=CDzBrNJXOT3yv3lpVrrnUSjO3FfAxPORH5iUA81ig9s&e=>

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_55&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JdiIZxBR5SXV83fLf52pghtwuzPd7taNtFVn9rwh-HaQ_D96riYyv53BjKvV4fKS&s=hlGjhXZJeuk0uOcA-S8FIg9LvHz4-O0vn94Ji2Gi5cY&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3J6IOPPSWASURYO2LTWMZW37ANCNFSM6AAAAAAS3KAVO4&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=JdiIZxBR5SXV83fLf52pghtwuzPd7taNtFVn9rwh-HaQ_D96riYyv53BjKvV4fKS&s=B8QBA0lzFZmyu4zpWCOAPsDOylj2wVyARACXbK1nfKE&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
