### ISSUE TITLE
mouse genome masks

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#57]
Hi,
Do you have mouse NOISE masks available to share? (mm10 preferred). If not, I can make my own.

And I'm curious if you have a SNP mask? Though I imagine it might be strain specific.

Thanks!

**Comment by fa8sanger** [comment]
Hi, you are right in that it would be very strain specific. A colleague of mine prepared one for a specific strain but it will work only for that one, and the mask is being tested. If you have enough SNP data should be easy to prepare one.


On 29 Dec 2022, at 19:38, gevro ***@***.******@***.***>> wrote:



Hi,
Do you have mouse NOISE masks available to share? (mm10 preferred). If not, I can make my own.

And I'm curious if you have a SNP mask? Though I imagine it might be strain specific.

Thanks!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_57&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=Zw5-0VR8z_U_7UQ3usi8So81T42TisKmMgprTK87AcY0ri6qflCHN7nukUsMAfN3&s=aQcGoJk8hcaYWUyJnqEPc7hFdkvjBl6loFqlAM99XN0&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3JYSHRXHR3RKS5BBE3WPXSCBANCNFSM6AAAAAATMK65XQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=Zw5-0VR8z_U_7UQ3usi8So81T42TisKmMgprTK87AcY0ri6qflCHN7nukUsMAfN3&s=6wiM8GF726de3qwbA5oFbmY7XvpNKMVZwo8VKSjQQvg&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thanks. Do you have a mouse NOISE mask at least?

**Comment by fa8sanger** [comment]
That would be quite strain-specific too. My colleague Adrian is working on a specific strain as I said. I am cc’ing Adrian in case he can help.

On 29 Dec 2022, at 23:14, gevro ***@***.******@***.***>> wrote:



Thanks. Do you have a mouse NOISE mask at least?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_57-23issuecomment-2D1367630730&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=6KkK_Nl-HmFaF1zzB-Zde_KS0MNCmzd3m5c4YWo_FbJwYyi7pfKk4iVVHZKzR_Jb&s=zM-JxQFIkAkBcmcyMteKxODqzfGSD8ApWnUqbDGtfLw&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3MMMMRRZJA7FT5P55DWPYLNZANCNFSM6AAAAAATMK65XQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=6KkK_Nl-HmFaF1zzB-Zde_KS0MNCmzd3m5c4YWo_FbJwYyi7pfKk4iVVHZKzR_Jb&s=40Wd20flvfFmAVJIQ5Kq9qMRAfEQXRtyXV1cVB02KPA&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thanks. Can the Nanoseq pipeline be run without a SNP file (i.e. specifying an empty bgzip/tabix file, since the dsa script requires a SNP file)? That would allow to run it in the meantime without a SNP file.

**Comment by fa8sanger** [comment]
Yes, just leave the SNP mask empty, it works.
