### ISSUE TITLE
Script base path does not exist or is not a directory: /home/ubuntu/bin

### ISSUE THREAD

**Issue by monagai** [cancerit/NanoSeq#71]
I'm running Nanoseq 3.5.0 using nextflow in a Docker container. 
I arranged a Dockerfile here because it does not include Java and nextflow.
I don't use module and sigularity. I use fastq as input.

My Nanoseq fails.
In .nextflow.log, I found the error message `Script base path does not exist or is not a directory: /home/ubuntu/bin`.

What is the "script base path"?
What should be placed under /home/ubuntu/bin? nextflow? Nanoseq scripts?

[detail]
```
....
Oct-18 08:03:19.091 [main] DEBUG nextflow.Session - Session UUID: 90cba058-7e70-4103-9731-6803b81e2238
Oct-18 08:03:19.091 [main] DEBUG nextflow.Session - Run name: voluminous_knuth
Oct-18 08:03:19.092 [main] DEBUG nextflow.Session - Executor pool size: 32
Oct-18 08:03:19.103 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Oct-18 08:03:19.111 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=96; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Oct-18 08:03:19.161 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 23.10.0 build 5889
  Created: 15-10-2023 15:07 UTC 
  System: Linux 3.10.0-1160.53.1.el7.x86_64
  Runtime: Groovy 3.0.19 on OpenJDK 64-Bit Server VM 11.0.20.1+1-post-Ubuntu-0ubuntu122.04
  Encoding: UTF-8 (UTF-8)
  Process: 1@937c69528046 [172.17.0.2]
  CPUs: 32 - Mem: 251.9 GB (123 GB) - Swap: 32 GB (22.2 GB)
Oct-18 08:03:19.203 [main] DEBUG nextflow.Session - Work-dir: /home/ubuntu/work [xfs]
Oct-18 08:03:19.204 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/ubuntu/bin
Oct-18 08:03:19.219 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Oct-18 08:03:19.236 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Oct-18 08:03:19.277 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Oct-18 08:03:19.320 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 33; maxThreads: 1000
Oct-18 08:03:19.434 [main] DEBUG nextflow.Session - Session start
Oct-18 08:03:22.578 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Oct-18 08:03:22.643 [main] INFO  nextflow.script.BaseScript - /home/ubuntu/info.csv
Oct-18 08:03:22.832 [main] INFO  nextflow.script.BaseScript - 
...
```
+ `/home/ubuntu/info.csv`: sample sheet csv I prepared for Nanoseq. 

I have read the following issue.
https://github.com/cancerit/NanoSeq/issues/42
It seems there is no answer.

**Comment by fa8sanger** [comment]
Hi, I am afraid the Nextflow script is not mature enough yet. I'd advise to run the pipeline directly with runNanoSeq.py. Not sure why #42 was closed without a reply, that's strange

**Comment by fa8sanger** [comment]
Good! Let me know if you encounter any problem and I’ll be happy to help

On 18 Oct 2023, at 12:39, Momoko NAGAI ***@***.***> wrote:



I really thank you for your quick reply. I will execute Nanoseq step by step following your advice.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_71-23issuecomment-2D1768268214&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=N1esaHRqEMouA-aQr1eBF2-Ik41arbAa4IAdv2nj-XIXbIdVLFD-I6VsAYHVtbk6&s=BoLJo0GdF8iotTRkMOxsXdWYP3GLUk4IhenG9JYq4nA&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3PDNY3VGJNNH7EBP6LX765Y3AVCNFSM6AAAAAA6FLOXS6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRYGI3DQMRRGQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=N1esaHRqEMouA-aQr1eBF2-Ik41arbAa4IAdv2nj-XIXbIdVLFD-I6VsAYHVtbk6&s=cZ_59dhktYmC2ctzy3ubEjUiYe5tshDsZEHLX7DyD2U&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA
