### ISSUE TITLE
Only unique mutations in trint_subs_obs_corrected.tsv

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#79]
Hi,
Just a minor comment - I saw that the total # of the number of mutations in trint_subs_obs_corrected.tsv does not equal the total # of mutations in the SNP VCF output and the mut_burden.tsv file. In the code I tracked down the discrepancy to only unique variants being output in trint_subs_obs_corrected.tsv. I'm not sure why that is, but just wanted to point it out in case this was not intentional.

Thanks!

**Comment by fa8sanger** [comment]
That’s right, to analyse mutational processes we only want to count each mutation once - if we see a mutation more than once we think it is more parsimonious to assume it’s the same mutation.

On 26 Nov 2023, at 02:02, gevro ***@***.***> wrote:



Hi,
Just a minor comment - I saw that the total # of the number of mutations in trint_subs_obs_corrected.tsv does not equal the total # of mutations in the SNP VCF output and the mut_burden.tsv file. In the code I tracked down the discrepancy to only unique variants being output in trint_subs_obs_corrected.tsv. I'm not sure why that is, but just wanted to point it out in case this was not intentional.

Thanks!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_79&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=5fRXcSG8GC8f8Jm2E-uX-dyRiqZRid27GJgcs7O7Y5jCl8wVTHSxFL-BTi3-ubMc&s=9m18Xarf6p6r5eh4pxTTDh_AUYlscf2RpIsY_NeKKng&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3MFBIOXP454GY3YBTLYGKPL3AVCNFSM6AAAAAA72P4ZWWVHI2DSMVQWIX3LMV43ASLTON2WKOZSGAYTAOBVHE4DIOI&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=5fRXcSG8GC8f8Jm2E-uX-dyRiqZRid27GJgcs7O7Y5jCl8wVTHSxFL-BTi3-ubMc&s=BA3YYH_SJKjAjupKW4Ol0yTyE5o5fK58Z6xX7_0sMCs&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA
