### ISSUE TITLE
Exclude contigs - unsafe

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/NanoSeq#8]
When excluding contigs you need to ensure that they matches are either exact or based on a wildcard indicator:

https://github.com/cancerit/NanoSeq/blob/c4e8052a1153802fc9d9ef045cb885b4fd46aab2/python/runBotSeq.py#L49

At present `MT` could match other items, especially as more species are added to the support matrix.

Recommend that all matching includes a "allow wildcard here" tag, e.g. `%`:

```
MT,GL%,hs37d5,NC_007605
```

The above requires exact match except for the GL item where `%` can be replaced with `.+` once internalised (you would also add the start/end anchor).  This matches how other tools in the cancerit stack would handle these items:

https://github.com/cancerit/cgpPindel/blob/6a31be2a82c531df2cadd76acf9d75c25797a38e/perl/lib/Sanger/CGP/Pindel/Implement.pm#L329-L340

**Comment by gevro** [comment]
Hi, You mentioned other species might be added for support. Will they be posted to Github, or available? The key challenge I'm assuming are the NOISE and SNP masks.
Thanks.

**Comment by fa8sanger** [comment]
Hi, We are not planning on adding those masks for other species. As long as samples are not contaminated the results will be good without the SNP mask. The NOISE mask doesn’t have much impact. From what we’ve seen, the quality of results depends on the quality of the assembly



On 6 Feb 2022, at 20:42, gevro ***@***.******@***.***>> wrote:



Hi, You mentioned other species might be added for support. Will they be posted to Github, or available? The key challenge I'm assuming are the NOISE and SNP masks.
Thanks.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_8-23issuecomment-2D1030910478&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=lt41wq9Q4uLK26T3rZkQADlrrLsXDLZVR8rYkoWJS2f1FhBLfGrVfYB0zLiYGCvJ&s=n9hIVR7N1DQ9rA_wSVxCnH-mbeX1W5_gc7yybA7mF7E&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3JYDC2FXSQKKUJFWQ3UZ3MMVANCNFSM4ZIFN3KA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=lt41wq9Q4uLK26T3rZkQADlrrLsXDLZVR8rYkoWJS2f1FhBLfGrVfYB0zLiYGCvJ&s=AL5aV4wJ4yP-QunXAJvk33m1kcRy_wRcRNHEHR_hyMU&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=lt41wq9Q4uLK26T3rZkQADlrrLsXDLZVR8rYkoWJS2f1FhBLfGrVfYB0zLiYGCvJ&s=l0Ws-Y91LARBPtSiAKPdggI4D1Ag-eXMWLO5aSPzHxk&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=lt41wq9Q4uLK26T3rZkQADlrrLsXDLZVR8rYkoWJS2f1FhBLfGrVfYB0zLiYGCvJ&s=-3mM9AtaLVPf5_1VjAAVuEK5SvIqbzchy2OFDGy8Rsw&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by gevro** [comment]
Thank you
