### ISSUE TITLE
Recommended -c setting

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#81]
Hi,
In a prior version, you said that you keep -c the same for both var and indel steps, and that you run it with -c 0, in issue: #50 

However, the default settings in the var and indel programs is -c 0.02.

Which setting is more stringent (i.e. removes more false positives): -c 0 or -c 0.02?
And what do you recommend we use? Is -c 0 ok for both var and indel, especially considering our recent finding of some indel artifacts on NovaseqX?

Thanks!

**Comment by gevro** [comment]
Just to add, so far we have been using -c 0 for both var and indel.

**Comment by fa8sanger** [comment]
-c 0.02 is less stringent, it allows up to 2% of reads with soft-clipping
This parameter usually doesn’t have much impact

On 30 Dec 2023, at 21:54, gevro ***@***.***> wrote:



Hi,
In a prior version, you said that you keep -c the same for both var and indel steps, and that you run it with -c 0, in issue: #50 [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_50&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=CDgzkSfRp8QUO0IYmRw5fef68PaW0Mb0cqQo_Kb_2op8sVzyWaFkH7fUSlXT_g7g&s=TSTF5zhs5tk-gh3Oot25BJAxZMMI9gLsQjqC4YaDbAo&e=>

However, the default settings in the var and indel programs is -c 0.02.

Which setting is more stringent (i.e. removes more false positives): -c 0 or -c 0.02?
And what do you recommend we use? Is -c 0 ok for both var and indel, especially considering our recent finding of some indel artifacts on NovaseqX?

Thanks!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_81&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=CDgzkSfRp8QUO0IYmRw5fef68PaW0Mb0cqQo_Kb_2op8sVzyWaFkH7fUSlXT_g7g&s=U6rDLdc60kSMFx1nw1faES04yxk056A8IlumXWWwjPY&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3P333XSO42ZOSEPWITYMCERNAVCNFSM6AAAAABBHYYXPKVHI2DSMVQWIX3LMV43ASLTON2WKOZSGA3DAOBWGYZDKMY&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=CDgzkSfRp8QUO0IYmRw5fef68PaW0Mb0cqQo_Kb_2op8sVzyWaFkH7fUSlXT_g7g&s=YcJncRwIH9h8q7_T--qK5C9yTMEp4szk536jhy00HU8&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA
