### ISSUE TITLE
quay.io docker

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#83]
Hi, Are the various docker versions on quay.io up to date and correspond to the github releases?
https://quay.io/repository/wtsicgp/nanoseq

Thanks!

**Comment by fa8sanger** [comment]
Those versions should be up to date. In the development version you can see that the Dockerfile file was modified 3 months ago

On 9 Jan 2024, at 15:52, gevro ***@***.***> wrote:



Hi, Are the various docker versions on quay.io up to date and correspond to the github releases?
https://quay.io/repository/wtsicgp/nanoseq [quay.io]<https://urldefense.proofpoint.com/v2/url?u=https-3A__quay.io_repository_wtsicgp_nanoseq&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=y9dHAqo2URj7LYsyPLJs224PgWRL5DMOayZP5mremIbqQYNhCpA5gx99WLmviju0&s=x6Gm1S1aBVvMSsGz5BiJTNkCXsMdaKB5PRHzP1e1H-s&e=>

Thanks!

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_83&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=y9dHAqo2URj7LYsyPLJs224PgWRL5DMOayZP5mremIbqQYNhCpA5gx99WLmviju0&s=P2uWQEncTNyctQzSb_lw1zGB9JjPYIFcemlbapKRghU&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3PIBLDWMTMVCKWHYTDYNVRVTAVCNFSM6AAAAABBTKINPCVHI2DSMVQWIX3LMV43ASLTON2WKOZSGA3TENRVGY3DGMI&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=y9dHAqo2URj7LYsyPLJs224PgWRL5DMOayZP5mremIbqQYNhCpA5gx99WLmviju0&s=tOXF43dCxiK4yLK7OvQJGV0e2LjF0TwymFIvX3zjVfE&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA
