### ISSUE TITLE
Minimum base quality

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#88]
Hi,
I see that var has a minimum consensus base quality parameter. Is there also a built-in minimum base quality per individual read for the base to be even used in the consensus step?

In some flow cells, there are regions of flow cell with low quality. Are the low quality bases in reads from those parts of the flow cell not going to be used at all to build the consensus, since there is a minimum base quality for individual reads? Or will they be used, which would cause them to lower the consensus? The former option might be better I am guessing.

Thanks

**Comment by fa8sanger** [comment]
Hi, your comment is very good. To answer your question we use all the reads, regardless their base qualities.

Your comment is also very well timed. During the past days I’ve been revisiting the impact of base qualities. Before explaining, let me make the point that BQs are platform-specific, and in our case also pipeline-specific because we have them compressed in ~5 or 6 different values. Basically what I am seeing is that a consensus BQ of 60 is too strict (in our case), and reducing this threshold is allowing us to get many more calls without an impact on error rates. This is still in investigation and, as I said, this adjustment may vary from platform to platform. Its impact will also depend on the duplicate rate as consensus BQs tend to increase with the number of reads in a read bundle.



On 30 Jan 2024, at 04:36, gevro ***@***.***> wrote:



Hi,
I see that var has a minimum consensus base quality parameter. Is there also a built-in minimum base quality per individual read for the base to be even used in the consensus step?

In some flow cells, there are regions of flow cell with low quality. Are the low quality bases in reads from those parts of the flow cell not going to be used at all to build the consensus, since there is a minimum base quality for individual reads? Or will they be used, which would cause them to lower the consensus? The former option might be better I am guessing.

Thanks

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_88&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=NvKJ-VnEAhrnalMzYcqXxzRZJRPWnbHlM-RvPsl6poTIHj34nSGkeNFz3X4FNIhN&s=RP1MWQIKjcSp9M-ZD7c1twoeX2xfxfEZqzH5G-qDTnw&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3P3SR76ULTJMT3OYWLYRB2FBAVCNFSM6AAAAABCQSGBLSVHI2DSMVQWIX3LMV43ASLTON2WKOZSGEYDMOJTGYZDENQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=NvKJ-VnEAhrnalMzYcqXxzRZJRPWnbHlM-RvPsl6poTIHj34nSGkeNFz3X4FNIhN&s=s0WoQMqlwPo21z3FBi1bM8EGxkDY4Hm5fiwSLzsFU3c&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA

**Comment by gevro** [comment]
Thanks for the update. Yes agree it will be platform-specific. However, I was referring also to something a bit different: a base quality filter for individual reads Vs. base quality filter for the consensus.

As far as I can tell there is only a base quality filter at the consensus level. Is there also a base quality filter at the level of individual reads that determines whether they are used to calculate the consensus? Or alternatively is there a filter for average base quality filter across the whole read to determine if a read is used to calculate the consensus?

The reason I think this might help efficiency is because some local parts of the flow cell can have reads with really low quality. Completely excluding these 'bad' reads from the consensus, or excluding specifically the low quality bases of low quality reads from the consensus may allow to create a consensus that passes the consensus base quality, whereas including these 'bad' reads in the consensus may pull down the consensus base quality below the consensus base quality threshold.

**Comment by fa8sanger** [comment]
Yes, I understood. We use all the reads and there is no argument to do what you would like to do. I am not sure excluding reads with low BQs would have much of an impact. If you look at how consensus BQ are calculated, low BQs have less impact on the final quality. But it would be worth testing. The easiest way to test this would be to apply a read filter upstream of the NanoSeq pipeline, removing reads not meeting certain threshold. If you ever try this I’d be curious to know if it works. If it improves efficiency we could implement it in the pipeline.

On 30 Jan 2024, at 13:34, gevro ***@***.***> wrote:



Thanks for the update. Yes agree it will be platform-specific. However, I was referring also to something a bit different: a base quality filter for individual reads Vs. base quality filter for the consensus.

As far as I can tell there is only a base quality filter at the consensus level. Is there also a base quality filter at the level of individual reads that determines whether they are used to calculate the consensus? Or alternatively is there a filter for average base quality filter across the whole read to determine if a read is used to calculate the consensus?

The reason I think this might help efficiency is because some local parts of the flow cell can have reads with really low quality. Completely excluding these 'bad' reads from the consensus, or excluding specifically the low quality bases of low quality reads from the consensus may allow to create a consensus that passes the consensus base quality, whereas including these 'bad' reads in the consensus may pull down the consensus base quality below the consensus base quality threshold.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_88-23issuecomment-2D1916861565&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=_06aeaVWjvTes804_6HV-fdDW7LYrf9YgG5YgPIuoKOkr0PHaeukDkHbrJ2pHkdY&s=8nR89sID--KOTYGFxKXZrNVsSo2oDcgRXI1lGCFISzg&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3P6X355QGP72STIPHLYRDZG5AVCNFSM6AAAAABCQSGBLSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJWHA3DCNJWGU&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=_06aeaVWjvTes804_6HV-fdDW7LYrf9YgG5YgPIuoKOkr0PHaeukDkHbrJ2pHkdY&s=ZG0V_RqMuDZBi8rWy2VvmjmBCoggtUPjL1YtTSkSlc4&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA

**Comment by gevro** [comment]
Makes sense thanks! Will let you know if we find evidence that a per-read base quality filter could help.
