### ISSUE TITLE
var -n parameter

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#90]
Hi,
In your paper you stated: "The average number of mismatches in a group of reads (forward or reverse) should not be higher than 2, either in the matched normal or the sample at hand. To avoid a bias in the filtering of mutation and reference calls, in cases in which a consensus base call is different from the reference, mismatches from that call are not considered when calculating the number of mismatches in the read."

1. Is this the same thing as the var -n parameter?
2. If so, is -n 3 (the default) the current recommended setting given that the paper implies -n 2?
3. What is the meaning of -n exactly: is it filtering to molecules with > 3 somatic mutation calls, or > 3 germline calls, or > 3 germline + somatic mutation calls? Is there a filter based on only the # of somatic mutation calls per molecule, and would this help remove residual artifacts?

Thanks

**Comment by fa8sanger** [comment]
Hi,

-n stands for the mean number of mismatches (NM tag in the bam file) in the read bundle. We don’t check whether the mismatches are germline SNPs, real somatic mutations or artefacts.
However, if the base being called is different from the reference (potential somatic mutation), then we don’t count it as a mismatch to avoid biases. In that case NM = NM-1

We believe -n 3 works very well and makes no difference compared to -n 2. For non-human species, when you are mapping to a more distant reference assembly or when the species has very high nucleotide diversity, you may need to adjust -n.




On 26 Feb 2024, at 21:32, gevro ***@***.***> wrote:



Hi,
In your paper you stated: "The average number of mismatches in a group of reads (forward or reverse) should not be higher than 2, either in the matched normal or the sample at hand. To avoid a bias in the filtering of mutation and reference calls, in cases in which a consensus base call is different from the reference, mismatches from that call are not considered when calculating the number of mismatches in the read."

  1.  Is this the same thing as the var -n parameter?
  2.  If so, is -n 3 (the default) the current recommended setting given that the paper implies -n 2?
  3.  What is the meaning of -n exactly: is it filtering to molecules with > 3 somatic mutation calls, or > 3 germline calls, or > 3 germline + somatic mutation calls? Is there a filter based on only the # of somatic mutation calls per molecule, and would this help remove residual artifacts?

Thanks

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_90&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=Oy0k17hAieJpA55UMe219NTM28VzhwCy1pMGKmnWw6xF5H3MqdNaSdDbQYQLdXG3&s=SaMirSPcEskz58bDsyfKeK2Ojq9LJ_5ppQT7F_1WVCU&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3LBLBZHLB2QN5EVBQLYVT5OJAVCNFSM6AAAAABD26NW2KVHI2DSMVQWIX3LMV43ASLTON2WKOZSGE2TKMJYGUZDGMY&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=Oy0k17hAieJpA55UMe219NTM28VzhwCy1pMGKmnWw6xF5H3MqdNaSdDbQYQLdXG3&s=n8NdAM51yiRk47HkeE2clbaKM2OpvUWDIhyN2I_WVto&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA

**Comment by gevro** [comment]
Thanks. Is there any filter in the pipeline based on only the # of somatic mutation calls per molecule?

**Comment by fa8sanger** [comment]
no but that could be applied a posteriori. The molecule identifier (RB id) is part of the VCF output


On 27 Feb 2024, at 13:50, gevro ***@***.***> wrote:



Thanks. Is there any filter in the pipeline based on only the # of somatic mutation calls per molecule?

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_90-23issuecomment-2D1966593799&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=fs4Obm64X8SIoyujgHbnGHZrNaaPUD-kcKxf0g_IRRUtP97y5YHz6d0BPpIQTDOh&s=4kvpMPJ8gV3PZIlzgGW4GyoFCZymW-Ug5VxNYEaS9zY&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3LZHEQ4R36DNIW3G3DYVXQCFAVCNFSM6AAAAABD26NW2KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRWGU4TGNZZHE&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=fs4Obm64X8SIoyujgHbnGHZrNaaPUD-kcKxf0g_IRRUtP97y5YHz6d0BPpIQTDOh&s=retK8nalAvpumVXFGdQ0XixFXUef2L27_n6Rv0RgnAY&e=>.
You are receiving this because you commented.Message ID: ***@***.***>




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA
