### ISSUE TITLE
Confirming meaning of 'total' in mut_burden.tsv

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#95]
Hi,
I just wanted to confirm: does the 'total' column in mut_burden.tsv contain the total number of duplex *base pairs* that were interrogated? i.e., is this the count of final base pairs (each base and its reverse complement = 1) or bases (each base and its reverse complement in the other strand are each counted separately)? I'm 99.9% sure it's the number of base pairs, but just wanted to be sure.

Thanks.

**Comment by fa8sanger** [comment]
Hi, it’s the number of duplex calls, as you said "each base and its reverse complement = 1”



On 30 Apr 2024, at 19:18, gevro ***@***.***> wrote:



Hi,
I just wanted to confirm: does the 'total' column in mut_burden.tsv contain the total number of duplex base pairs that were interrogated? i.e., is this the count of final base pairs (each base and its reverse complement = 1) or bases (each base and its reverse complement in the other strand are each counted separately)? I'm 99.9% sure it's the number of base pairs, but just wanted to be sure.

Thanks.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_95&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=guzX6C4daCRf_g0fJKrlJdV1af5Y7quC0e68-QCuvqNYrvrQDMtGDoXapHxYtN0E&s=zez6PwhrqaoR6ysH4Aub5G7m3yQCxbJKmjaEh7eakVQ&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3PV7GEARS5BRJ3K473Y77N7ZAVCNFSM6AAAAABHAYKGW2VHI2DSMVQWIX3LMV43ASLTON2WKOZSGI3TEMJYGQ3DQOI&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=guzX6C4daCRf_g0fJKrlJdV1af5Y7quC0e68-QCuvqNYrvrQDMtGDoXapHxYtN0E&s=mHVgG8VbsmUu_jQC2q82WR0B3_YIVu88cPrWigFxJ6w&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.
