### ISSUE TITLE
gnomad filtering of indels

### ISSUE THREAD

**Issue by gevro** [cancerit/NanoSeq#97]
Does the SNP mask for hg38 also contain population frequent indels, or only SNPs? The paper methods suggest only SNPs but wanted to confirm.

**Comment by fa8sanger** [comment]
The SNP mask does contain indels, only those with certain AF and passing all gnomad filters. Indels with high AF but failing filters go to the NOISE mask

On 10 May 2024, at 11:54, gevro ***@***.***> wrote:



Does the SNP mask for hg38 also contain population frequent indels, or only SNPs? The paper methods suggest only SNPs but wanted to confirm.

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_NanoSeq_issues_97&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=H8LWvQP6mZG3sbG8-UrZlb3J5QtOsrmsBgr64RYukejUp0x9h2ZXq4qj2QZhviYC&s=9Fh4DvbICNZiuDDiXF5Io7YYfXY7oenXv0S3beAQpwM&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADNUT3NLZLQKCSTYNM4H2ALZBSRO3AVCNFSM6AAAAABHQNORVOVHI2DSMVQWIX3LMV43ASLTON2WKOZSGI4DSNBZHA2DSNQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=v9-R7fUmjpv-9Zaqyk1nlnlOC3qPkTEJz5tyYxg2uec&m=H8LWvQP6mZG3sbG8-UrZlb3J5QtOsrmsBgr64RYukejUp0x9h2ZXq4qj2QZhviYC&s=7C186yhFoWNphwihHK3rttleNIjV_dh9ZdILpfPsxhQ&e=>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


----------------------------------------------------------------------
The Wellcome Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is Wellcome Sanger Institute, Wellcome Genome Campus, Hinxton, CB10 1SA.
